import {expect,it,vi} from 'vitest';
import {startAccountBootstrap} from './accountBootstrap';
import {loadUserSetupWithRetry} from './settings';
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function fixture(){const pending:Array<()=>void>=[];let fail=false;const from=vi.fn((table:string)=>({select:()=>({eq:()=>({single:()=>new Promise(resolve=>pending.push(()=>resolve(fail?{error:{code:'42501'}}:{error:null,data:table==='profiles'?{onboarding_completed:true}:{strength_enabled:true,cardio_enabled:true,mobility_enabled:true,weight_enabled:true,preferred_weight_unit:'lb'}})))})})}));return {client:{from} as never,from,pending,fail:()=>{fail=true;},recover:()=>{fail=false;}};}
it('deduplicates concurrent setup and waits for both slow settings/profile reads',async()=>{const f=fixture(),a=vi.fn(),b=vi.fn();startAccountBootstrap(f.client,'a',a);startAccountBootstrap(f.client,'a',b);expect(f.from).toHaveBeenCalledTimes(2);f.pending.shift()!();await flush();expect(a).not.toHaveBeenCalled();f.pending.shift()!();await flush();expect(a).toHaveBeenCalledOnce();expect(b).toHaveBeenCalledOnce();});
it('ignores prior account results after sign-out and switching accounts',async()=>{const f=fixture(),a=vi.fn(),b=vi.fn();const stop=startAccountBootstrap(f.client,'a',a);stop();startAccountBootstrap(f.client,'b',b);for(const resolve of f.pending)resolve();await flush();expect(a).not.toHaveBeenCalled();expect(b).toHaveBeenCalledWith(expect.objectContaining({userId:'b',setup:expect.any(Object)}));});
it('allows Retry without refreshing after a permanent error is corrected',async()=>{const f=fixture(),publish=vi.fn();f.fail();startAccountBootstrap(f.client,'a',publish);f.pending.splice(0).forEach(resolve=>resolve());await flush();expect(publish.mock.lastCall?.[0].error.code).toBe('42501');f.recover();startAccountBootstrap(f.client,'a',publish);f.pending.splice(0).forEach(resolve=>resolve());await flush();expect(publish.mock.lastCall?.[0].setup.onboardingCompleted).toBe(true);});
it('does not query optional Groups/privacy during core bootstrap',async()=>{const f=fixture();const request=loadUserSetupWithRetry(f.client,'a');f.pending.forEach(resolve=>resolve());await request;expect(f.from.mock.calls.map(call=>call[0])).toEqual(['user_settings','profiles']);});
