import {expect,it,vi} from 'vitest';
import {authCallback,completeAuthCallback,confirmationMessage,confirmationRedirect,resendVerification,verificationResponse} from './emailConfirmation';
it('detects confirmation, root legacy hash callbacks and recovery separately',()=>{expect(authCallback('https://production.test/auth/confirm?code=a')).toMatchObject({active:true,code:'a',recovery:false});expect(authCallback('https://production.test/#access_token=a&refresh_token=b&type=signup').active).toBe(true);expect(authCallback('https://production.test/auth/reset-password?code=a').recovery).toBe(true);expect(authCallback('https://production.test/').active).toBe(false);});
it('exchanges a PKCE code once across Strict Mode subscribers',async()=>{let resolve!:(value:unknown)=>void;const exchangeCodeForSession=vi.fn(()=>new Promise(r=>{resolve=r;})),client={auth:{exchangeCodeForSession}};const callback=authCallback('https://production.test/auth/confirm?code=a');const a=completeAuthCallback(client as never,callback),b=completeAuthCallback(client as never,callback);expect(a).toBe(b);expect(exchangeCodeForSession).toHaveBeenCalledExactlyOnceWith('a');resolve({data:{session:{user:{id:'a'}}},error:null});await a;});
it('accepts legacy tokens without a second PKCE exchange',async()=>{const setSession=vi.fn(async()=>({data:{session:{}},error:null}));await completeAuthCallback({auth:{setSession}} as never,authCallback('https://production.test/#access_token=a&refresh_token=b&type=signup'));expect(setSession).toHaveBeenCalledWith({access_token:'a',refresh_token:'b'});});
it.each(['otp_expired','access_denied','email_already_confirmed'])('retains callback rejection %s without accepting an old session',async code=>{const exchangeCodeForSession=vi.fn();await expect(completeAuthCallback({auth:{exchangeCodeForSession}} as never,authCallback('https://production.test/auth/confirm?error_code='+code))).rejects.toMatchObject({code});expect(exchangeCodeForSession).not.toHaveBeenCalled();expect(confirmationMessage(code)).toMatch(/expired|confirmed/);});
it('rejects incomplete tokens and empty links',async()=>{await expect(completeAuthCallback({} as never,authCallback('https://production.test/auth/confirm#access_token=a'))).rejects.toMatchObject({code:'malformed'});});
it('surfaces code-exchange failure rather than trusting a cached login',async()=>{await expect(completeAuthCallback({auth:{exchangeCodeForSession:async()=>({error:{code:'bad_code_verifier'}})}} as never,authCallback('https://production.test/?code=a'))).rejects.toMatchObject({code:'bad_code_verifier'});});
it('preserves production origin and uses generic resend responses',async()=>{expect(confirmationRedirect('https://production.test')).toBe('https://production.test/auth/confirm');for(const resend of [vi.fn(async()=>({error:null})),vi.fn(async()=>({error:{code:'user_not_found'}})),vi.fn(async()=>{throw Error('offline');})]){expect(await resendVerification({auth:{resend}} as never,' email@test.com ','https://production.test')).toBe(verificationResponse);expect(resend).toHaveBeenCalledWith({type:'signup',email:'email@test.com',options:{emailRedirectTo:'https://production.test/auth/confirm'}});}});
