import {expect,it,vi} from 'vitest';
import type {Session} from '@supabase/supabase-js';
import {recoveryLocation,recoveryRedirect,recoveryView,requestPasswordReset,resetResponse,passwordError} from './passwordRecovery';
import {startAuth,type StartupState} from './startupAuth';
it('recognizes browser and installed-PWA recovery routes without retaining credentials',()=>{expect(recoveryLocation('https://example.test/auth/reset-password')).toEqual({active:true,invalid:false});expect(recoveryLocation('https://example.test/#type=recovery')).toEqual({active:true,invalid:false});expect(recoveryLocation('https://example.test/auth/reset-password#error_code=otp_expired')).toEqual({active:true,invalid:true});expect(recoveryLocation('https://example.test/auth/reset-password?error=access_denied')).toEqual({active:true,invalid:true});expect(recoveryLocation('https://example.test/leaderboards#invite=example')).toEqual({active:false,invalid:false});});
it('uses exact same-origin redirect paths for local and production environments',()=>{expect(recoveryRedirect('http://localhost:5173')).toBe('http://localhost:5173/auth/reset-password');expect(recoveryRedirect('https://example.test')).toBe('https://example.test/auth/reset-password');});
it('does not reveal account existence or propagate server errors in reset responses',async()=>{for(const response of [{error:null},{error:{code:'user_not_found'}},{error:{code:'over_email_send_rate_limit'}}]){const resetPasswordForEmail=vi.fn(async()=>response);expect(await requestPasswordReset({auth:{resetPasswordForEmail}} as never,' user@example.test ','https://example.test')).toBe(resetResponse);expect(resetPasswordForEmail).toHaveBeenCalledWith('user@example.test',{redirectTo:'https://example.test/auth/reset-password'});}expect(await requestPasswordReset({auth:{resetPasswordForEmail:async()=>{throw Error('offline');}}} as never,'user@example.test','https://example.test')).toBe(resetResponse);});
it('gates password entry on completed validation and handles invalid or absent sessions',()=>{expect(recoveryView(true,false,false)).toBe('loading');expect(recoveryView(false,false,false)).toBe('invalid');expect(recoveryView(false,true,true)).toBe('invalid');expect(recoveryView(false,true,false)).toBe('password');});
it('preserves recovery intent through deferred validation and ignores stale validation after sign-out',async()=>{
 let event!:(event:string,session:Session|null)=>void;const jobs:Array<()=>void>=[],states:StartupState[]=[],onRecovery=vi.fn();let resolve!:(value:unknown)=>void;
 const getUser=vi.fn(()=>new Promise(r=>{resolve=r;}));const client={auth:{onAuthStateChange:(cb:typeof event)=>{event=cb;return {data:{subscription:{unsubscribe:vi.fn()}}};},getSession:()=>new Promise(()=>{}),getUser}};
 const stop=startAuth(client as never,state=>states.push(state),{onRecovery,defer:job=>jobs.push(job)});
 event('PASSWORD_RECOVERY',{user:{id:'fixture'}} as Session);expect(onRecovery).toHaveBeenCalledOnce();expect(getUser).not.toHaveBeenCalled();expect(states.at(-1)?.loading).toBe(true);jobs.shift()!();event('SIGNED_OUT',null);resolve({data:{user:{id:'fixture'}},error:null});await Promise.resolve();await Promise.resolve();expect(states.at(-1)).toEqual({session:null,loading:false,error:''});stop();
});
it('recovery validation completes without refresh and token refresh retains the ready account',async()=>{
 let event!:(event:string,session:Session|null)=>void;const states:StartupState[]=[],jobs:Array<()=>void>=[],onRecovery=vi.fn();const session={user:{id:'fixture'}} as Session;
 const client={auth:{onAuthStateChange:(cb:typeof event)=>{event=cb;return {data:{subscription:{unsubscribe:vi.fn()}}};},getSession:()=>new Promise(()=>{}),getUser:async()=>({data:{user:{id:'fixture'}},error:null})}};
 const stop=startAuth(client as never,state=>states.push(state),{onRecovery,defer:job=>jobs.push(job)});event('PASSWORD_RECOVERY',session);jobs.shift()!();await Promise.resolve();await Promise.resolve();expect(states.at(-1)).toMatchObject({loading:false,session});event('TOKEN_REFRESHED',session);expect(states.at(-1)).toMatchObject({loading:false,session});expect(onRecovery).toHaveBeenCalledOnce();stop();
});
it('returns safe password validation and reauthentication messages',()=>{expect(passwordError('same_password')).toContain('different');expect(passwordError('reauthentication_needed')).toContain('email code');expect(passwordError('bad_jwt')).toContain('expired');});
