import{describe,expect,it,vi}from'vitest';import{loadUserSetupWithRetry}from'./settings'
const client=(failures:number)=>{let calls=0;const result=()=>({select:()=>({eq:()=>({maybeSingle:async()=>{calls++;if(calls<=failures)return{data:null,error:null};return calls%2?{data:{strength_enabled:true,cardio_enabled:true,mobility_enabled:false,weight_enabled:true,preferred_weight_unit:'lb'},error:null}:{data:{onboarding_completed:false},error:null}}})})});return{from:vi.fn(()=>result()),calls:()=>calls}}
describe('account bootstrap retry',()=>{it('recovers from briefly missing companion rows',async()=>{const mock=client(2);const wait=vi.fn(async()=>{});const setup=await loadUserSetupWithRetry(mock as never,'user',{attempts:3,wait});expect(setup.preferredWeightUnit).toBe('lb');expect(wait).toHaveBeenCalled()});it('does not retry permanent errors',async()=>{const permanent={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:null,error:{code:'42501',message:'RLS denied'}})})})})};const wait=vi.fn(async()=>{});await expect(loadUserSetupWithRetry(permanent as never,'user',{wait})).rejects.toMatchObject({code:'42501'});expect(wait).not.toHaveBeenCalled()})})

it.each([{code:'42703'},{code:'42P01'},{code:'PGRST204'}])('does not retry missing schema %s',async error=>{const c={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:null,error})})})})};const wait=vi.fn(async()=>{});await expect(loadUserSetupWithRetry(c as never,'a',{wait})).rejects.toMatchObject(error);expect(wait).not.toHaveBeenCalled();});
it('recovers from a transient gateway failure',async()=>{let calls=0;const c={from:(table:string)=>({select:()=>({eq:()=>({maybeSingle:async()=>++calls<=2?{error:{message:'Unavailable'},status:503}:{error:null,data:table==='profiles'?{onboarding_completed:true}:{preferred_weight_unit:'lb'}}})})})};const wait=vi.fn(async()=>{});expect((await loadUserSetupWithRetry(c as never,'a',{wait})).onboardingCompleted).toBe(true);expect(wait).toHaveBeenCalledOnce();});

it('does not treat cardinality errors as proof that companion rows are missing',async()=>{const c={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:null,error:{code:'PGRST116'}})})})})};const wait=vi.fn(async()=>{});await expect(loadUserSetupWithRetry(c as never,'a',{wait})).rejects.toMatchObject({code:'PGRST116'});expect(wait).not.toHaveBeenCalled();});
it('leaves persistently absent rows blocked and never fabricates onboarding or repairs silently',async()=>{const rpc=vi.fn(),c={rpc,from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:null,error:null})})})})};const wait=vi.fn(async()=>{});await expect(loadUserSetupWithRetry(c as never,'a',{wait})).rejects.toMatchObject({code:'ACCOUNT_ROWS_PENDING'});expect(wait).toHaveBeenCalledTimes(3);expect(rpc).not.toHaveBeenCalled();});
