export type SupabaseErrorLike={code?:string;message?:string;details?:string;hint?:string;status?:number;operation?:string}
export type DataErrorKind='schema'|'authentication'|'permission'|'network'|'query'|'unexpected'

export function classifyDataError(error:unknown,online=true):DataErrorKind{const value=error as SupabaseErrorLike,message=value.message?.toLowerCase()??'',code=value.code??'';if(['42P01','42703','42883','PGRST202','PGRST204'].includes(code)||message.includes('does not exist')||message.includes('schema cache')&&/(table|column|function|relation)/.test(message))return'schema';if(value.status===401||code==='PGRST301'||message.includes('jwt')||message.includes('authentication required'))return'authentication';if(code==='42501'||message.includes('permission denied')||message.includes('row-level security')||message.includes('insufficient privilege'))return'permission';if(['PGRST200','PGRST201','PGRST_CARDINALITY'].includes(code)||message.includes('relationship')||message.includes('cardinality')||message.includes('could not find a relationship'))return'query';if(!online||message.includes('failed to fetch')||/^(typeerror: )?load failed$/.test(message)||message.includes('networkerror')||message.includes('network request')||message.includes('dns')||message.includes('timed out')||message.includes('timeout'))return'network';return'unexpected'}

export function safeSupabaseDiagnostic(feature:string,operation:string,error:unknown){if(!import.meta.env.DEV)return;const value=(error??{}) as SupabaseErrorLike;console.error('Supabase query failed',{feature,operation,code:/^[A-Za-z0-9_]{1,40}$/.test(value.code??'')?value.code:undefined,message:classifyDataError(value),status:typeof value.status==='number'?value.status:undefined})}

/** Classify permanent errors first, even while offline. Never retry arbitrary errors. */
export function transientDataError(error:unknown){const value=(error??{}) as SupabaseErrorLike;const kind=classifyDataError(value);if(['schema','permission','query','authentication'].includes(kind))return false;return kind==='network'||[0,408,429,500,502,503,504].includes(value.status??-1)||['PGRST000','PGRST001','PGRST002','57014'].includes(value.code??'')||value instanceof TypeError&&/fetch|network/i.test(value.message);}

export function dataLoadMessage(feature:string,error:unknown,online=true){switch(classifyDataError(error,online)){case'schema':return`${feature} needs a database schema update before this data can load.`;case'authentication':return`Your session has expired. Sign out, sign back in, and retry ${feature}.`;case'permission':return`Your account does not have permission to read ${feature} data. Sign out, sign back in, and retry.`;case'network':return`${feature} could not reach Supabase. Check your connection and retry.`;case'query':return`${feature} received an invalid relationship response. Refresh the app; if it continues, check the developer console.`;default:return`${feature} data could not load because of an unexpected database response. Retry or check the developer console.`}}

export function relationObject<T>(value:unknown,relationship:string):T|null{if(value===null||value===undefined)return null;if(Array.isArray(value))throw Object.assign(new Error(`Unexpected cardinality for ${relationship}`),{code:'PGRST_CARDINALITY'});if(typeof value!=='object')throw Object.assign(new Error(`Invalid embedded response for ${relationship}`),{code:'PGRST_CARDINALITY'});return value as T}
