// Local browser regression fixture. No live client or account is used.
import React from 'react';
import {createRoot} from 'react-dom/client';
import {ProgressPrivacy} from '../../src/features/groups/ProgressPrivacy';
import {GroupsFeature} from '../../src/features/groups/GroupsFeature';
import {MobileNavigation} from '../../src/components/MobileNavigation';
import {displayGroupCode} from '../../src/features/groups/groupCode';
import {StrengthProgress} from '../../src/features/progress/ProgressFeature';
import '../../src/index.css';
window.requestAnimationFrame=callback=>setTimeout(()=>callback(performance.now()),16);
window.cancelAnimationFrame=clearTimeout;
const snapshotMode=new URLSearchParams(location.search).get('snapshot');
const root=createRoot(document.getElementById('root')),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),checks=[];
const assert=(condition,name)=>{checks.push({name,pass:Boolean(condition)});};
const setValue=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
const field=name=>[...document.querySelectorAll('label')].find(label=>label.textContent.startsWith(name)&&label.querySelector('input:not([readonly])'))?.querySelector('input:not([readonly])');
const button=text=>[...document.querySelectorAll('[role=alertdialog] button'),...document.querySelectorAll('button')].find(button=>button.textContent===text);
async function typeInto(input,text){input.focus();let value='';for(const char of text){value+=char;setValue.call(input,value);input.setSelectionRange(value.length,value.length);input.dispatchEvent(new Event('input',{bubbles:true}));await wait(20);assert(document.activeElement===input&&input.isConnected&&input.selectionStart===value.length&&input.value===value,'focus and caret after '+value);}input.setSelectionRange(0,8);setValue.call(input,'Sunday'+input.value.slice(8));input.setSelectionRange(6,6);input.dispatchEvent(new Event('input',{bubbles:true}));await wait(20);assert(document.activeElement===input&&input.selectionStart===6,'selection replacement keeps caret');input.setSelectionRange(3,3);input.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));await wait(20);assert(document.activeElement===input&&input.selectionStart===3,'rerenders preserve selected caret');const before=input.value;setValue.call(input,before.slice(0,2)+before.slice(3));input.setSelectionRange(2,2);input.dispatchEvent(new Event('input',{bubbles:true}));await wait(20);assert(input.selectionStart===2&&document.activeElement===input,'backspace edit keeps focus');}
const token='ABCD2FGH',calls=[];let listed=[],failJoin=false,sharing=true,deferSummary=false,pendingSummary;
const summary=id=>({name:id==='created'?'Saturday Strength Club':'Joined Friends',through:'2026-09-15',members:[{member_id:'self',display_name:'Friend',role:id==='created'?'owner':'member',is_self:true,sharing_progress:sharing}],sets:sharing?[{member_id:'self',muscle:'Chest',total:99}]:[],prs:[],cardio:[],activities:[]});
const client={from:()=>({select:()=>({order:async()=>({data:listed,error:null}),eq:()=>({single:async()=>({data:null,error:null})})})}),rpc:async(name,args)=>{calls.push({name,args});
 if(name==='create_private_group_with_code'){listed=[{id:'created',name:'Saturday Strength Club'}];return {data:{ok:true,group_id:'created',code:token},error:null};}
 if(name==='get_private_group_code')return {data:token,error:null};
 if(name==='get_group_progress_sharing')return {data:sharing,error:null};
 if(name==='set_group_progress_sharing'){sharing=args.p_enabled;return {data:sharing,error:null};}
 if(name==='private_group_summary'){const result={data:summary(args.p_group_id),error:null};if(deferSummary){deferSummary=false;return await new Promise(resolve=>{pendingSummary=()=>resolve(result);});}return result;}
 if(name==='join_private_group_code'){if(failJoin)return {data:{ok:false},error:null};listed=[...listed,{id:'joined',name:'Joined Friends'}];return {data:{ok:true,group_id:'joined'},error:null};}
 throw Error('Unmocked RPC '+name);
}};
async function choose(label,text){const select=[...document.querySelectorAll('.custom-select')].find(node=>node.querySelector('.field-label')?.textContent===label);if(!select)throw Error('Missing dropdown '+label);const details=select.closest('details');if(details)details.open=true;select.querySelector('button').scrollIntoView({block:'center'});select.querySelector('button').click();await wait(20);const option=[...document.querySelectorAll('[role=option]')].find(option=>option.querySelector('strong')?.textContent===text);if(!option)throw Error('Missing option '+text+' in '+label);const menu=option.closest('[role=listbox]').getBoundingClientRect();assert(menu.left>=0&&menu.right<=innerWidth&&menu.top>=0&&menu.bottom<=innerHeight,'dropdown inside viewport '+label);option.click();await wait(100);}
(async()=>{
 root.render(<GroupsFeature client={client} userId="local-fixture"/>);await wait(400);button('Create Group').click();await wait(40);const name=field('Group name');await typeInto(name,'Saturday Strength Club');assert(field('Group name')===name,'same group-name DOM node');await typeInto(field('Display name'),'Saturday Training Friend');button('Cancel').click();await wait(30);button('Join a Group').click();await wait(30);await typeInto(field('Group Code'),'abcd-2fgh');button('Cancel').click();await wait(30);
 // Creation and join operate exclusively against the local RPC fixture.
 button('Create Group').click();await wait(40);setValue.call(field('Group name'),'Saturday Strength Club');field('Group name').dispatchEvent(new Event('input',{bubbles:true}));await wait(20);
 document.querySelector('[role=alertdialog] input[type=checkbox]').click();button('Create Group').click();await wait(500);
 const manage=[...document.querySelectorAll('summary')].find(node=>node.textContent==='Manage Group');assert(!!manage&&!manage.parentElement.open,'code hidden outside Manage Group');const codeCalls=calls.filter(call=>call.name==='get_private_group_code').length;manage.click();await wait(50);assert(calls.filter(call=>call.name==='get_private_group_code').length===codeCalls,'opening Manage Group does not fetch code');
 assert(document.querySelector('.group-code-value')?.value===displayGroupCode(token),'created group displays entire code, no UUID or hash');
 assert(!!button('Copy Code')&&!!button('Share Code'),'copy and share controls');const codeCard=document.querySelector('.group-code-value');assert(codeCard.scrollHeight<=codeCard.clientHeight,'entire group code visible without internal scrolling');
 assert(document.documentElement.scrollWidth<=innerWidth,'group code screen has no horizontal overflow');
 manage.click();await wait(30);assert(!manage.parentElement.open&&!document.querySelector('.group-code-value'),'closing Manage Group hides code');manage.click();await wait(30);
 if(snapshotMode==='code'){document.getElementById('result').textContent=JSON.stringify({checks:checks.length,failures:checks.filter(check=>!check.pass)});return;}
 button('Join a Group').click();await wait(30);const joinInput=field('Group Code');joinInput.focus();setValue.call(joinInput,'  '+displayGroupCode(token).toLowerCase().replaceAll('-',' - ')+'  ');joinInput.dispatchEvent(new Event('input',{bubbles:true}));await wait(30);assert(document.activeElement===joinInput,'pasted code retains focus');document.querySelector('[role=alertdialog] input[type=checkbox]').click();failJoin=true;button('Join Group').click();await wait(100);assert(document.querySelector('[role=alert]')?.textContent.includes('Unable to join with this code'),'generic invalid join result');assert(field('Group Code')===joinInput,'validation preserves code DOM node');failJoin=false;button('Join Group').click();await wait(400);
 assert(document.querySelector('h2')?.textContent==='Joined Friends','successful join opens returned group');assert(!document.querySelector('.group-code-value'),'old owner code cleared on join');assert(calls.filter(call=>call.name==='join_private_group_code').every(call=>call.args.p_code===token),'pasted code canonicalized for RPC');
 root.render(<><ProgressPrivacy client={client} userId="local-fixture"/><GroupsFeature client={client} userId="local-fixture"/></>);await wait(400);
 const toggle=document.querySelector('[role=switch]');assert(toggle.getAttribute('aria-checked')==='true','privacy default enabled');assert(document.body.textContent.includes('99 sets'),'shared progress visible');
 deferSummary=true;window.dispatchEvent(new Event('focus'));await wait(60);toggle.click();await wait(250);assert(toggle.getAttribute('aria-checked')==='false','opt out saved');assert(!document.body.textContent.includes('99 sets'),'opt out clears cached totals');assert(document.body.textContent.includes('Progress hidden'),'membership retained with progress hidden');pendingSummary?.();await wait(150);assert(!document.body.textContent.includes('99 sets'),'late old summary cannot restore hidden totals');toggle.click();await wait(250);assert(document.body.textContent.includes('99 sets'),'re-enabling restores existing aggregates');assert(calls.filter(call=>call.name==='set_group_progress_sharing').every(call=>Object.keys(call.args).join(',')==='p_enabled'),'no user ID supplied to privacy RPC');
 root.render(<GroupsFeature client={{...client,from:()=>({select:()=>({order:async()=>({data:[],error:null}),eq:()=>({single:async()=>({data:null,error:null})})})})}} userId="other-account"/>);await wait(100);assert(!document.querySelector('.group-code-value')&&!document.body.textContent.includes('Joined Friends'),'account switch clears private state');
 const rows=[225,185,235,175,240].map((weight,index)=>({id:String(index),exercise_id:'bench',tracking_type:'repetitions',weight,reps:5,set_order:index,weight_unit:'lb',load:null,distance:null,distance_unit:null,laps:null,duration_seconds:null,exercise:{id:'bench',name:'Bench Press',tracking_type:'repetitions'},workout:{performed_at:'2026-09-01T12:00:00',created_at:'2026-09-01',location:{id:'gym',name:'Gym'}}}));
 root.render(<div className="app-frame"><main className="content"><StrengthProgress rows={rows} unit="lb"/></main></div>);await wait(500);await choose('Graph mode','All Logged Sets');assert(document.documentElement.scrollWidth<=innerWidth,'progress screen has no horizontal overflow');
 for(const style of ['Straight','Smooth']){await choose('Line Style',style);const markers=[...document.querySelectorAll('.strength-set-marker')];assert(markers.length===5,style+' has five markers');assert(new Set(markers.map(dot=>dot.getAttribute('cx'))).size===5,style+' separates duplicate dates');for(let index=0;index<markers.length;index++){for(const action of ['focus','click','hover']){const marker=document.querySelectorAll('.strength-set-marker')[index];if(action==='focus')marker.focus();else marker.dispatchEvent(new MouseEvent(action==='hover'?'mouseover':'click',{bubbles:true}));await wait(100);const detail=document.querySelector('[role=status]');assert(detail?.textContent.includes(rows[index].weight+' lb')&&detail?.textContent.includes('Bench Press'),style+' '+action+' exact set '+index+(action==='focus'?' focused='+document.activeElement?.tagName+' value='+detail?.textContent:''));}}}
 // All module combinations, representative safe-area values and larger text.
 for(const safe of [0,20,34,48])for(const scale of [1,1.25])for(let mask=0;mask<16;mask++){
 document.documentElement.style.fontSize=16*scale+'px';const enabled={strength:!!(mask&1),cardio:!!(mask&2),flexibility:!!(mask&4),weight:!!(mask&8)};
 root.render(<div className="app-frame"><MobileNavigation enabled={enabled} screen="leaderboards" go={()=>{}} icon={()=> <svg width="19" height="19" aria-hidden="true"/>}/></div>);await wait(5);const nav=document.querySelector('.bottom-nav');nav.style.paddingBottom=safe+'px';nav.style.height=(76*scale+safe)+'px';
 assert(document.documentElement.scrollWidth<=innerWidth,'no horizontal overflow '+mask+' '+safe+' '+scale);
 for(const key of ['Home','Progress','Leaderboards'])assert(!!button(key),'reachable '+key+' '+mask);
 assert(!button('Settings'),'no Settings navigation '+mask);
 if(safe===0&&scale===1&&document.querySelector('.bottom-nav [aria-haspopup="dialog"]')){document.querySelector('.bottom-nav [aria-haspopup="dialog"]').click();await wait(20);const dialog=document.querySelector('[role=alertdialog]');assert(!!dialog&&!dialog.textContent.includes('Settings'),'More contains enabled modules only');for(const [key,label] of [['cardio','Cardio'],['flexibility','Flexibility'],['weight','Bodyweight']])assert(dialog.textContent.includes(label)===enabled[key],'More visibility '+label+' '+mask);button('Close').click();await wait(20);}
 for(const item of nav.querySelectorAll('button')){const r=item.getBoundingClientRect();assert(r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight-safe+1&&r.height>=44&&r.width>=44,'visible touch target '+item.textContent+' '+mask+' '+safe+' '+scale);}
 }
 document.documentElement.style.fontSize='';
 document.getElementById('result').textContent=JSON.stringify({checks:checks.length,failures:checks.filter(check=>!check.pass)});
})().catch(error=>{document.getElementById('result').textContent=JSON.stringify({error:String(error),stack:error.stack,checks:checks.length,failures:checks.filter(check=>!check.pass)});});
