import React,{Suspense} from 'react';
import {FeatureBoundary} from '../../src/components/FeatureBoundary';
import {retryableLazy} from '../../src/lib/retryableLazy';
import {createRoot} from 'react-dom/client';
import {ProgressFeature} from '../../src/features/progress/ProgressFeature';
import '../../src/index.css';
const wait=ms=>new Promise(r=>setTimeout(r,ms)),checks=[],offenders=[];
const assert=(pass,name)=>checks.push({pass:!!pass,name});
const rows=Array.from({length:50},(_,i)=>({id:String(i),exercise_id:'bench',tracking_type:'repetitions',weight:100+i%10,reps:i%2?1:5,set_order:i,weight_unit:'lb',exercise:{id:'bench',name:'Bench Press',major_muscle_group:'Chest',tracking_type:'repetitions'},workout:{id:'w'+i,performed_at:new Date(2026,Math.floor(i/5),1+i%5,12).toISOString(),created_at:'2026-09-16',location:{id:'gym',name:'Gym'}}}));
const cardio=[3,1,2].map(i=>({id:String(i),performed_at:'2026-09-0'+i+'T12:00:00',created_at:'2026-09-16',duration_seconds:300,distance:2,distance_unit:i%2?'miles':'kilometers',activity:{name:'Running'},location:null,location_id:null}));
const flex=[3,1,2].map(i=>({id:String(i),performed_at:'2026-09-0'+i+'T12:00:00',activity:{name:'Stretch',tracking_type:'time',areas:[]},sets:[{duration_seconds:30,reps:null}]}));
const weight=[3,1,2].map(i=>({id:String(i),measured_at:'2026-09-0'+i+'T12:00:00',weight:150,weight_unit:'lb',period:'morning'}));
const client={from:table=>{const data=table==='strength_sets'?rows:table==='cardio_sessions'?cardio:table==='mobility_sessions'?flex:weight;const q={};for(const method of ['select','eq','gte','lte','order','range','ilike'])q[method]=()=>q;q.then=(yes,no)=>Promise.resolve({data,error:null,count:data.length}).then(yes,no);return q;}};
const root=createRoot(document.getElementById('root'));
async function choose(label,text){const trigger=[...document.querySelectorAll('.custom-select')].find(n=>n.querySelector('.field-label')?.textContent===label)?.querySelector('button');if(!trigger)return;trigger.click();await wait(30);[...document.querySelectorAll('[role=option]')].find(n=>n.textContent.startsWith(text))?.click();await wait(80);}
function ticks(name){for(const axis of document.querySelectorAll('.recharts-xAxis-tick-labels')){const labels=[...axis.querySelectorAll('.recharts-cartesian-axis-tick-value')],rects=labels.map(n=>n.getBoundingClientRect()).sort((a,b)=>a.left-b.left);assert(new Set(labels.map(n=>n.textContent)).size===labels.length,name+' unique ticks');assert(rects.every((r,i)=>!i||r.left>=rects[i-1].right-1),name+' no tick overlap');}}
const button=text=>[...document.querySelectorAll('button')].find(n=>n.textContent===text);
function layout(name){const width=document.documentElement.clientWidth;assert(document.documentElement.scrollWidth<=width,name+' no page overflow');const frame=document.querySelector('.app-frame');assert(frame.getBoundingClientRect().width<=width&&frame.getBoundingClientRect().width>=width-12,name+' stable frame');for(const node of document.querySelectorAll('.recharts-wrapper')){const r=node.getBoundingClientRect();assert(r.width>100&&r.right<=width&&r.height>=200,name+' readable chart');}if(document.documentElement.scrollWidth>width)offenders.push({name,width,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(n=>{const r=n.getBoundingClientRect();return r.right>width+1&&!n.closest('.overflow-x-auto')}).slice(0,14).map(n=>({tag:n.tagName,cls:n.getAttribute('class'),width:n.getBoundingClientRect().width,right:n.getBoundingClientRect().right}))});}
(async()=>{let importCalls=0;const RetryFeature=retryableLazy(async()=>{if(++importCalls===1)throw new TypeError('Failed to fetch dynamically imported module');return {default:()=> <p>Recovered feature</p>};});root.render(<FeatureBoundary><Suspense fallback={<p>Loading fixture</p>}><RetryFeature/></Suspense></FeatureBoundary>);for(let i=0;i<100&&!button('Retry');i++)await wait(20);assert(!!button('Retry'),'failed lazy feature offers Retry');button('Retry').click();await wait(400);assert(document.body.textContent.includes('Recovered feature')&&importCalls===2,'lazy Retry succeeds without page refresh');root.render(<div className="app-frame"><main className="content"><ProgressFeature client={client} userId="fixture" enabled={{strength:true,cardio:true,flexibility:true,weight:true}} weightUnit="lb"/></main></div>);await wait(700);
for(const tab of ['Strength','Cardio','Flexibility','Bodyweight']){button(tab).click();await wait(500);layout(tab);ticks(tab);if(tab==='Strength'){for(const mode of ['One Rep Max','Rep Weight','All Logged Sets']){await choose('Graph mode',mode);layout(mode);ticks(mode);}for(const aggregation of ['Weekly','Monthly']){await choose('Aggregation',aggregation);layout(aggregation);ticks(aggregation);}await choose('Time period','Custom Range');}for(const control of document.querySelectorAll('.chart-controls'))control.open=true;await wait(100);layout(tab+' controls');for(const input of document.querySelectorAll('input[type=date]')){input.focus();layout(tab+' date focus');}if(tab==='Strength'){for(const legend of document.querySelectorAll('.muscle-trend button[aria-pressed]')){legend.click();await wait(10);assert(legend.getAttribute('aria-pressed')==='false','legend hides '+legend.textContent);} }for(const input of document.querySelectorAll('input:not([type=checkbox]),textarea')){assert(parseFloat(getComputedStyle(input).fontSize)>= (CSS.supports('-webkit-touch-callout','none')?16:13.6),tab+' input font');}for(const trigger of document.querySelectorAll('[aria-haspopup=listbox]')){trigger.click();await wait(40);layout(tab+' dropdown');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));document.querySelector('.select-dismiss')?.click();}if(tab==='Cardio'){for(const metric of ['Duration','Distance','Average speed','Average pace']){const input=[...document.querySelectorAll('label')].find(n=>n.textContent.startsWith('Metric'))?.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,metric);input.dispatchEvent(new Event('input',{bubbles:true}));await wait(30);[...document.querySelectorAll('[role=option]')].find(n=>n.textContent.startsWith(metric))?.click();await wait(50);layout('Cardio '+metric);const labels=[...document.querySelectorAll('.recharts-xAxis-tick-labels .recharts-cartesian-axis-tick-value')].map(n=>n.textContent);assert(labels.join(',')==='9/1,9/2,9/3','Cardio '+metric+' performed chronology '+JSON.stringify(labels));}}const svg=document.querySelector('.recharts-wrapper > .recharts-surface');assert(!svg||svg.getBoundingClientRect().width>100,tab+' chart remains visible');}
document.getElementById('result').textContent=JSON.stringify({checks:checks.length,failures:checks.filter(c=>!c.pass),offenders});})().catch(e=>document.getElementById('result').textContent=JSON.stringify({error:String(e)}));
