import React from 'react';
import {createRoot} from 'react-dom/client';
import {AuthContext} from '../../src/lib/authContext';
import App from '../../src/App';
import '../../src/index.css';
const snapshot=new URLSearchParams(location.search).get('snapshot');
const root=createRoot(document.getElementById('root')),checks=[],errors=[];
window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
const wait=ms=>new Promise(r=>setTimeout(r,ms)),assert=(pass,name)=>checks.push({name,pass:!!pass});
const buttons=()=>[...document.querySelectorAll('button')];
const button=text=>buttons().find(n=>n.textContent.trim()===text||n.getAttribute('aria-label')===text||n.querySelector('strong')?.textContent===text);
const field=label=>[...document.querySelectorAll('label')].find(n=>n.textContent.replace(n.querySelector('textarea')?.textContent??'','').trim()===label)?.querySelector('input,textarea');
const click=async text=>{const node=button(text);if(!node)throw Error('Missing '+text+': '+document.body.textContent);node.click();await wait(130);};
const enter=async(node,value)=>{if(!node)throw Error('Missing field after '+checks.at(-1)?.name+'; labels: '+[...document.querySelectorAll('label')].map(n=>n.textContent.trim()).join('|'));Object.getOwnPropertyDescriptor(node.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));await wait(60);};
const fit=name=>assert(document.documentElement.scrollWidth<=innerWidth,name+' fits '+innerWidth);
const def=(id,name,tracking_type='repetitions',load_mode='weight_reps',progression_direction='higher_is_better')=>({id,user_id:'u',name,tracking_type,load_mode,progression_direction,major_muscle_group:'Chest',is_compound:true,archived:false,created_at:'',updated_at:''});
const definitions=[def('bench','Bench Press'),def('pull','Pull Up','repetitions','reps_only'),def('assist','Assisted Pull Up','repetitions','weight_reps','lower_is_better'),def('sled','Sled Push','distance')];
let workouts=[],calls=[],locations=[{id:'gym',name:'Home Gym',is_default:false,archived:false}],failLocation=false;
window.__fixtureClient={
 async rpc(name,p){if(name==='get_release_acknowledgement')return{data:true,error:null};if(name==='list_private_groups')return{data:[],error:null};if(name!=='save_strength_workout')return{data:[],error:null};calls.push(structuredClone(p));const id=p.p_workout.id??'w'+calls.length;let w=workouts.find(x=>x.id===id);if(!w){w={id,created_at:new Date().toISOString()};workouts.unshift(w);}Object.assign(w,p.p_workout,{id,location:locations.find(l=>l.id===p.p_workout.location_id)??null});w.sets=p.p_sets.map((s,i)=>({...s,id:s.id??id+'-s'+i,exercise:definitions.find(e=>e.id===s.exercise_id)}));return{data:id,error:null};},
 from(table){let id,ids,insert,update,start=0,end=499;const result=()=>{let data=table==='profiles'?[{onboarding_completed:true}]:table==='user_settings'?[{strength_enabled:true,cardio_enabled:true,mobility_enabled:true,weight_enabled:true,preferred_weight_unit:'lb'}]:table==='exercises'?definitions:table==='locations'?locations:table==='strength_workouts'?workouts:table==='strength_sets'?workouts.flatMap(w=>w.sets.map(s=>({...s,workout:{id:w.id,performed_at:w.performed_at,created_at:w.created_at,location:w.location}}))):table==='cardio_activities'?[{id:'run',name:'Running',archived:false}]:table==='mobility_activities'?[{id:'stretch',name:'Hamstring Stretch',tracking_type:'time',archived:false,areas:[]}]:[];if(id)data=data.filter(x=>x.id===id);if(ids)data=data.filter(x=>ids.includes(x.id));return{data:data.slice(start,end+1),count:data.length,error:null};};const q={select(){return q},eq(key,v){if(key==='id')id=v;return q},in(_k,v){ids=v;return q},order(){return q},gte(){return q},lte(){return q},is(){return q},ilike(){return q},range(a,b){start=a;end=b;return q},insert(p){insert=p;return q},update(p){update=p;return q},async maybeSingle(){return{...result(),data:result().data[0]};},async single(){if(insert&&table==='locations'){if(failLocation)return{error:Error('offline')};const row={...insert,id:'loc'+locations.length,archived:false,is_default:false};locations.push(row);return{data:row,error:null};}if(update&&table==='locations'){Object.assign(locations.find(l=>l.id===id),update);return{data:{id},error:null};}return{...result(),data:result().data[0]};},then(resolve,reject){return Promise.resolve(result()).then(resolve,reject)}};return q;}
};
async function render(path='/strength/new'){history.replaceState({},'',path);root.render(<AuthContext.Provider value={{session:{user:{id:'u'}},loading:false,signOut:async()=>{}}}><App key={Math.random()}/></AuthContext.Provider>);for(let i=0;i<100;i++){await wait(100);if(document.querySelector('.bottom-nav')&&!/Loading module|Loading Leaderboards|Loading your/.test(document.querySelector('main')?.textContent??''))break;}await wait(200);}
async function choose(name){await enter(field('Exercise'),name);const row=[...document.querySelectorAll('.picker-row')].find(n=>n.querySelector('strong')?.textContent===name);if(!row)throw Error('Missing exercise '+name);row.click();await wait(100);}
async function nav(label){const n=document.querySelector(`.bottom-nav [aria-label="${label}"]`);if(n)n.click();else{document.querySelector('.bottom-nav [aria-haspopup="dialog"]').click();await wait(80);const option=[...document.querySelectorAll('[role=alertdialog] button')].find(n=>n.textContent.trim()===label);if(!option)throw Error('Missing navigation '+label);option.click();}await wait(250);}
const noOverall=()=>assert(!/workout duration/i.test(document.body.textContent),'overall duration absent');
void(async()=>{
 await render();assert(button('Save workout'),'new Strength opens real form');assert(!button('+ Add Another Exercise'),'new entry has no add-exercise action');noOverall();
 await choose('Bench Press');await enter(field('Reps'),'0');await enter(field('Weight (lb)'),'300');
 await click('Exercise notes');fit('Expanded notes');await enter(field('Exercise notes'),'Keep this workout note');await click('Exercise notes');
 await click('Set notes');await enter(field('Set notes'),'Attempt note');await click('Set notes');
 await click('Duplicate');assert(document.querySelectorAll('.set-card').length===2,'duplicate adds set');assert(document.querySelectorAll('.notes-toggle[aria-expanded=true]').length===1,'duplicated existing note starts expanded');
 await click('+ Add Set');assert(document.querySelectorAll('.set-card').length===3,'add set remains available');const sets=[...document.querySelectorAll('.set-card')];sets[2].querySelectorAll('input')[0].value='';sets[2].querySelector('button:last-child').click();await wait(60);assert(document.querySelectorAll('.set-card').length===2,'remove affects only selected set');
 const before=[...document.querySelectorAll('.set-card input')].map(n=>n.value);
 field('Location').click();await wait(80);fit('Location dropdown');await click('+ Add new location');fit('Location creation dialog');await click('Cancel');assert(document.activeElement===field('Location'),'cancel restores selector focus');assert(field('Location').placeholder==='No location','cancel preserves selection');field('Location').click();await wait(60);await click('+ Add new location');await enter(field('Location name'),'  HOME   gym ');await click('Save location');assert(field('Location').placeholder==='Home Gym','duplicate selects existing location');assert(document.body.textContent.includes('already available'),'duplicate is explained');
 field('Location').click();await wait(60);await enter(field('Location'),'no matching location');field('Location').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));await wait(30);assert(document.activeElement===button('+ Add new location'),'keyboard reaches creation action with no matches');assert(button('+ Add new location').getAttribute('role')!=='option','creation is an action, not a fake option');assert(button('+ Add new location').getBoundingClientRect().height>=44,'location action has 44px target');await click('+ Add new location');await enter(field('Location name'),'New Gym');failLocation=true;await click('Save location');assert(field('Location name').value==='New Gym','failed creation retains name');assert(document.querySelector('[role=alert]'),'retryable inline location error');failLocation=false;await click('Save location');assert(field('Location').placeholder==='New Gym','new location selected');assert(button('+ Add new location')===undefined,'successful creation closes dropdown');assert(JSON.stringify(before)===JSON.stringify([...document.querySelectorAll('.set-card input')].map(n=>n.value)),'location creation preserves all unsaved sets');
 await nav('Strength');assert(document.querySelector('[role=alertdialog]')?.textContent.includes('Discard unsaved'),'dirty module navigation prompts');await click('Stay');assert(field('Reps').value==='0','Stay preserves attempt');
 await click('Save workout');assert(document.querySelector('h1')?.textContent==='Lift Logged','prominent success');assert(calls[0].p_sets.length===2&&calls[0].p_sets.every(s=>s.reps===0),'zero saves in all sets');assert(calls[0].p_workout.notes==='Keep this workout note'&&calls[0].p_sets.every(s=>s.notes==='Attempt note'),'collapsed notes save');assert(calls[0].p_workout.duration_seconds===null,'new overall duration neutral');assert(document.querySelectorAll('.saved-set').length===2,'success lists every set');assert(document.querySelectorAll('.pr-first,.pr-weight,.pr-reps').length===0,'attempt success has no badges');assert(!/undefined|NaN/.test(document.querySelector('main').textContent),'no missing numeric text');assert(!button('Log Another Exercise'),'no log-another action');noOverall();fit('Strength success');if(snapshot==='success'){document.getElementById('result').textContent=JSON.stringify({checks:checks.length,failures:checks.filter(c=>!c.pass),errors});return;}
 await click('Edit Entry');assert(field('Reps').value==='0','success edits exact zero record');assert(document.querySelectorAll('.notes-toggle[aria-expanded=true]').length===3,'existing notes expanded independently');const oldCards=[...document.querySelectorAll('.set-card')];await enter(oldCards[1].querySelector('textarea'),'second identity note');oldCards[0].querySelectorAll('button')[1].click();await wait(80);assert(document.querySelector('.set-card textarea').value==='second identity note','removing first set preserves the second stable note');await click('Save changes');assert(calls.at(-1).p_sets[0].notes==='second identity note','stable remaining note reaches save payload');await click('Edit Entry');await nav('Strength');assert(!document.querySelector('[role=alertdialog]'),'unchanged edit navigates immediately');assert(document.querySelector('h1')?.textContent==='Strength','same tab resets edit');
 await click('Strength History');noOverall();assert(document.querySelector('main').textContent.includes('Attempt'),'history shows attempts');await nav('Strength');assert(document.querySelector('h1')?.textContent==='Strength','same tab resets history');
 // Legacy multi-exercise editing keeps hidden duration and every row.
 workouts=[{id:'legacy',performed_at:'2020-02-03T12:00:00Z',created_at:'2020-02-03T12:00:00Z',duration_seconds:1234,notes:'old',location:null,sets:[{id:'s1',exercise_id:'bench',tracking_type:'repetitions',set_order:1,weight:100,reps:5,exercise:definitions[0]},{id:'s2',exercise_id:'pull',tracking_type:'repetitions',set_order:2,weight:null,reps:3,exercise:definitions[1]}]}];
 await render('/strength');document.querySelector('main button.surface-card')?.click();await wait(100);await click('Edit workout');assert(button('+ Add Another Exercise'),'legacy retains multi-exercise editor');noOverall();await enter(field('Exercise notes'),'edited old note');await click('Save changes');assert(calls.at(-1).p_workout.duration_seconds===1234&&calls.at(-1).p_sets.length===2,'legacy save preserves hidden duration and rows');
 for(const name of ['Pull Up','Assisted Pull Up','Sled Push']){await render();await choose(name);if(name==='Sled Push'){await enter(field('Load (lb)'),'80');await enter(field('Distance / lap'),'20');await enter(field('Duration (seconds, optional)'),'45');await click('+ Add Set');const row=document.querySelectorAll('.set-card')[1];for(const [label,value] of [['Load (lb)','90'],['Distance / lap','30']])await enter([...row.querySelectorAll('label')].find(n=>n.textContent.trim()===label).querySelector('input'),value);}else {await enter(field('Reps'),'0');if(name.startsWith('Assisted'))await enter(field('Assistance (lb)'),'25');}await click('Save workout');assert(document.querySelector('h1')?.textContent==='Lift Logged',name+' saves');if(name==='Sled Push')assert(calls.at(-1).p_sets[0].duration_seconds===45&&calls.at(-1).p_sets.length===2,'distance time and multiple sets retained');else assert(document.querySelector('main').textContent.includes('Attempt'),name+' attempt presentation');fit(name+' success');await nav('Strength');assert(document.querySelector('h1')?.textContent==='Strength','navigation exits '+name+' success');}
 // Successful entries after attempts establish the correct baseline and badges.
 workouts=workouts.filter(w=>w.sets.every(s=>s.exercise_id!=='bench'||s.reps===0));
 for(const [weight,reps,badge] of [['225','5','First Entry'],['250','5','Weight PR'],['250','6','Rep PR']]){await render();await choose('Bench Press');await enter(field('Weight (lb)'),weight);await enter(field('Reps'),reps);await click('Save workout');assert(document.querySelector('h1')?.textContent==='Lift Logged','successful weighted save');assert(document.querySelector('main').textContent.includes(badge),'successful confirmation '+badge);assert(!document.querySelector('.saved-set .eyebrow'),'one-set success omits set numbering');}
 const modules=[['strength','Strength'],['cardio','Cardio'],['flexibility','Flexibility'],['weight','Bodyweight'],['progress','Progress'],['groups','Leaderboards']];
 for(const [path,label] of modules){for(const nested of ['new','history','edit','detail','success','manage']){await render('/'+path+'/'+nested);await nav(label);assert(location.pathname==='/'+path,label+' returns home from '+nested);assert(!document.querySelector('[role=alertdialog]'),label+' unchanged route has no discard prompt');fit(label+' home');}}
 for(const [path,label,input] of [['cardio','Cardio','Notes (optional)'],['flexibility','Flexibility','Notes (optional)'],['weight','Bodyweight','Notes (optional)']]){await render('/'+path+'/new');const text=document.querySelector('main textarea')??field(input);await enter(text,'unsaved');await nav(label);assert(document.querySelector('[role=alertdialog]')?.textContent.includes('Discard unsaved'),label+' protects changes');await click('Stay');assert(text.value==='unsaved',label+' Stay retains changes');await nav(label);await click('Discard and Go to Module Home');assert(location.pathname==='/'+path&&!document.querySelector('main textarea'),label+' discard reaches home');}
 await render('/cardio');await enter(document.querySelector('[aria-label="New cardio activity"]'),'unsaved activity');await nav('Cardio');assert(document.querySelector('[role=alertdialog]')?.textContent.includes('Discard unsaved'),'Cardio management protects changes');await click('Discard and Go to Module Home');assert(document.querySelector('[aria-label="New cardio activity"]').value==='','Cardio management resets');
 await render('/flexibility');await click('+ New');await enter(field('Name'),'unsaved stretch');await nav('Flexibility');assert([...document.querySelectorAll('[role=alertdialog]')].some(n=>n.textContent.includes('Discard unsaved')),'Flexibility management protects changes');await click('Discard and Go to Module Home');assert(!field('Name'),'Flexibility navigation closes editor');
 await render('/groups');await click('Create Group');await enter(field('Group name'),'unsaved group');await nav('Leaderboards');assert([...document.querySelectorAll('[role=alertdialog]')].at(-1)?.textContent.includes('Discard unsaved'),'Groups discard dialog is above local dialog');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(60);assert(field('Group name')?.value==='unsaved group','Escape stays without closing underlying group draft');await nav('Leaderboards');await click('Discard and Go to Module Home');assert(!document.querySelector('[role=alertdialog]'),'Groups navigation closes local dialogs');
 await render('/cardio/new');assert(document.querySelector('[aria-label="Duration Seconds"]'),'Cardio duration retained');field('Location (optional)').click();await wait(80);assert(button('+ Add new location'),'Cardio shares location dropdown action');await nav('Home');assert(location.pathname==='/','Home returns dashboard');
 await render('/flexibility/new');await enter(field('Stretch'),'Hamstring');const option=document.querySelector('[role=option]');option?.click();await wait(80);assert(document.querySelector('[aria-label*="duration"]'),'timed Flexibility duration retained');
 assert(!document.querySelector('select'),'no native selects');assert(errors.length===0,'no runtime errors: '+errors.join('; '));
 document.getElementById('result').textContent=JSON.stringify({checks:checks.length,failures:checks.filter(c=>!c.pass),errors});
})().catch(error=>document.getElementById('result').textContent=JSON.stringify({error:String(error),checks:checks.length,failures:checks.filter(c=>!c.pass),errors}));
