// Local fixtures only; the fixture server blocks nonlocal connections.
import React from 'react';
import {AuthContext} from '../../src/lib/authContext';
import {createRoot} from 'react-dom/client';
import {CardioFeature} from '../../src/features/cardio/CardioFeature';
import {CardioProgress,StrengthProgress} from '../../src/features/progress/ProgressFeature';
import {SetsByMuscleGroup} from '../../src/features/strength/SetsByMuscleGroup';
import {ReleaseAnnouncement} from '../../src/components/ReleaseAnnouncement';
import '../../src/index.css';
const runtimeErrors=[];window.addEventListener('error',event=>runtimeErrors.push(event.message));window.addEventListener('unhandledrejection',event=>runtimeErrors.push(String(event.reason)));
const root=createRoot(document.getElementById('root')),checks=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const assert=(value,name)=>checks.push({name,pass:Boolean(value)});
const button=text=>[...document.querySelectorAll('button')].find(node=>node.textContent===text);
const input=label=>[...document.querySelectorAll('label')].find(node=>node.textContent.startsWith(label))?.querySelector('input');
const setValue=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
async function enter(node,value){setValue.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));await wait(30);}
async function choose(label,text){const field=[...document.querySelectorAll('.custom-select')].find(node=>node.querySelector('.field-label')?.textContent===label);if(field)field.querySelector('button').click();else await enter(input(label),text);await wait(30);const option=[...document.querySelectorAll('[role=option]')].find(node=>node.querySelector('strong')?.textContent===text);if(!option)throw Error('Missing '+text);option.click();await wait(150);}
const render=async element=>{root.render(<div className="app-frame"><main className="content">{element}</main></div>);await wait(350);};
const fits=name=>assert(document.documentElement.scrollWidth<=innerWidth,name+' has no page overflow');
const rows=[[100,4],[110,3],[105,6],[150,1],[100,12],[105,8],[110,4],[115,5]].map(([weight,reps],i)=>({id:String(i),set_order:i,exercise_id:'e',tracking_type:'repetitions',weight,reps,weight_unit:'lb',load:null,distance:null,distance_unit:null,laps:null,duration_seconds:null,exercise:{id:'e',name:'Bench Press',tracking_type:'repetitions',major_muscle_group:'Chest'},workout:{id:String(i),performed_at:'2026-09-22T12:00:00',created_at:'2026-09-22T12:00:00',location:null}}));
void(async()=>{
 await render(<StrengthProgress rows={rows} unit="lb"/>);await choose('Graph mode','Rep Weight');
 let markers=[...document.querySelectorAll('.strength-set-marker')];assert(markers.length===5,'Rep Weight renders all five required milestones');assert(new Set(markers.map(node=>node.getAttribute('cx'))).size===5,'same-day milestones have separate X coordinates');
 for(const [i,weight] of [100,105,105,110,115].entries()){document.querySelectorAll('.strength-set-marker')[i].dispatchEvent(new MouseEvent('click',{bubbles:true}));await wait(30);assert(document.querySelector('[role=status]')?.textContent.includes(weight+' lb'),'exact milestone tooltip '+i);}
 fits('Rep Weight');
 const assisted=rows.map((row,i)=>({...row,weight:[60,55,50,45,40,35,30,25][i],exercise:{...row.exercise,name:'Assisted fixture',progression_direction:'lower_is_better'}}));
 await render(<StrengthProgress key="assisted" rows={assisted} unit="lb"/>);assert(document.body.textContent.includes('Assistance Progress'),'assisted progression label');
 const mode=[...document.querySelectorAll('.custom-select')].find(node=>node.querySelector('.field-label')?.textContent==='Graph mode');mode.querySelector('button').click();await wait(30);assert(![...document.querySelectorAll('[role=option]')].some(node=>node.textContent.includes('One Rep Max')),'assistance excludes One Rep Max');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));fits('Assistance');
 const months=rows.slice(0,4).map((row,i)=>({...row,workout:{...row.workout,performed_at:['2026-07-01','2026-07-20','2026-08-22','2026-09-22'][i]}}));
 await render(<SetsByMuscleGroup rows={months} start="2026-07-01" end="2026-09-30" location=""/>);
 assert(document.querySelector('.recharts-line-dots')?.querySelectorAll('circle').length===3,'Monthly passes three aggregated points to Recharts');assert(document.body.textContent.includes('Jul 2026'),'monthly axis uses month names');fits('Muscle trends');
 await choose('Aggregation','Weekly');assert(!document.body.textContent.includes('Yearly'),'no Yearly muscle trend');fits('Weekly trends');
 const cardio=rows.slice(0,3).map((row,i)=>({id:row.id,performed_at:['2026-09-22','2026-09-20','2026-09-21'][i],duration_seconds:60,step_count:[1000,null,500][i],distance:null,distance_unit:null,speed:null,incline:null,difficulty:null,activity:{name:'Walking'},location:null,location_id:null}));
 await render(<CardioProgress rows={cardio}/>);await choose('Metric','Steps');assert(document.body.textContent.includes('1,500')&&document.body.textContent.includes('750'),'step total and measured-entry average');fits('Steps');
 await choose('Step aggregation','Monthly');assert(document.querySelector('.recharts-line-dots')?.querySelectorAll('circle').length===1,'monthly Steps aggregates measured entries');document.querySelector('.chart-controls').open=true;await enter(input('Y minimum (steps)'),'0');await enter(input('Y maximum (steps)'),'2000');await wait(100);assert([...document.querySelectorAll('section[aria-label="Steps Progress"] svg text')].some(node=>node.textContent==='2000'),'Steps applies the shared custom Y maximum');
 const captured=[];let stored=[];
 const client={from(table){const q={select(){return q},eq(){return q},order(){return q},ilike(){return q},range:async()=>({data:stored,count:stored.length,error:null}),insert(payload){captured.push(payload);stored=[{...payload,id:'saved',activity:{name:'Walking'},location:null}];return q},update(payload){captured.push(payload);stored=[{...stored[0],...payload}];return q},delete(){stored=[];return q},single:async()=>({data:{id:'saved'},error:null}),then(resolve){return Promise.resolve({data:table==='cardio_activities'?[{id:'walk',name:'Walking',archived:false}]:[],error:null}).then(resolve)}};return q;}};
 // oxlint-disable-next-line react/only-export-components -- executable isolated fixture, not a Fast Refresh module
 function CardioFixture(){const [create,setCreate]=React.useState(true);return <AuthContext.Provider value={{session:null,loading:false,signOut:async()=>{}}}><CardioFeature client={client} userId="fixture" create={create} onExitCreate={()=>setCreate(false)}/></AuthContext.Provider>;}
 await render(<CardioFixture/>);
 await wait(600);const steps=input('Steps');if(!steps)throw Error('Cardio fixture: '+document.body.textContent+' errors: '+JSON.stringify(runtimeErrors));assert(steps?.inputMode==='numeric'&&steps?.type==='text','Steps uses numeric keyboard and unmodified text');steps.focus();await enter(steps,'1e3');assert(steps.value==='1e3'&&document.activeElement===steps,'invalid typing does not change input or focus');
 await choose('Activity','Walking');document.querySelector('[aria-label="Duration Seconds"] [data-value="1"]').click();await wait(150);
 button('Save Cardio Entry').click();await wait(80);assert(document.querySelector('[role=alert]')?.textContent.includes('Steps must be')&&captured.length===0,'scientific notation is rejected before saving');
 await enter(steps,'2147483647');assert(steps.value==='2147483647','maximum integer retains all digits');fits('Cardio form');
 button('Save Cardio Entry').click();await wait(500);assert(captured[0]?.step_count===2147483647,'save payload preserves exact maximum steps');assert(document.body.textContent.includes('2,147,483,647 steps'),'success displays supplied steps');button('Done / View History').click();await wait(200);assert(document.body.textContent.includes('2,147,483,647 steps'),'reloaded history displays steps');if(!button('Edit'))throw Error('History fixture: '+document.body.textContent+' errors: '+JSON.stringify(runtimeErrors));button('Edit').click();await wait(100);assert(input('Steps')?.value==='2147483647','history edit reloads exact steps');await enter(input('Steps'),'');button('Save Cardio Entry').click();await wait(400);assert(captured.at(-1)?.step_count===null,'clearing optional steps saves null');assert(captured.at(-1)?.duration_seconds===captured[0]?.duration_seconds&&captured.at(-1)?.activity_id===captured[0]?.activity_id,'step edit preserves duration and activity');button('Done / View History').click();await wait(200);button('Delete').click();await wait(100);[...document.querySelectorAll('[role=alertdialog] button')].find(node=>node.textContent.startsWith('Delete')).click();await wait(300);assert(stored.length===0,'deleting an entry removes its optional steps');
 let saved=false,ackCalls=0,finishAck;const releaseClient={rpc:async name=>name==='get_release_acknowledgement'?{data:saved,error:null}:(ackCalls++,await new Promise(resolve=>{finishAck=success=>{if(success)saved=true;resolve({error:success?null:{code:'fixture'}});};}))};
 await render(<ReleaseAnnouncement client={releaseClient} userId="fixture" ready onLeaderboards={()=>{}}/>);
 const dialog=document.querySelector('[role=alertdialog]');assert(dialog?.textContent.includes('Progressive Overload 2.1'),'new announcement title');assert(dialog?.contains(document.activeElement),'announcement manages initial focus');fits('2.1 announcement');button('Close').click();button('Close').click();await wait(100);assert(ackCalls===1&&!!document.querySelector('[role=alertdialog]')&&!saved,'duplicate dismissal is blocked while server is pending');finishAck(false);await wait(100);assert(document.querySelector('[role=alert]')?.textContent.includes('retry'),'failed acknowledgement stays open with inline retry');button('Retry dismissal').click();await wait(50);finishAck(true);await wait(100);assert(saved&&!document.querySelector('[role=alertdialog]'),'dismissal waits for server acknowledgement');await render(<ReleaseAnnouncement key="reload" client={releaseClient} userId="fixture" ready onLeaderboards={()=>{}}/>);assert(!document.querySelector('[role=alertdialog]'),'remount honors durable server acknowledgement');
 assert(runtimeErrors.length===0,'no uncaught browser errors');document.getElementById('result').textContent=JSON.stringify({checks:checks.length,failures:checks.filter(check=>!check.pass)});
})().catch(error=>{document.getElementById('result').textContent=JSON.stringify({error:String(error),checks:checks.length,failures:checks.filter(check=>!check.pass)});});
