import {expect,it} from 'vitest';
import {exerciseTableRows,defaultExerciseSort} from './exerciseSort';
const point=(id:string,exerciseId:string,date='2026-09-01',locationId='gym')=>({id,exerciseId,date,periodLabel:date,locationId,source:'dated',achievement:undefined as string|undefined});
const exercises:Array<[string,string]>=[['z','Zulu'],['b','  bench   PRESS '],['a','Alpha']];
it('defaults to most actual sets, deduplicates IDs, and resolves ties by normalized names',()=>{expect(defaultExerciseSort).toBe('sets');const points=[point('1','z'),point('2','z'),point('3','b'),point('4','a'),point('4','a')];expect(exerciseTableRows(exercises,points,{periods:['2026-09']}).items.map(row=>[row.id,row.count])).toEqual([['z',2],['a',1],['b',1]]);});
it('normalizes alphabetical names and search before sorting and paging',()=>{const points=[point('1','z'),point('2','b')];expect(exerciseTableRows(exercises,points,{periods:['2026-09'],sort:'alphabetical'}).items.map(row=>row.id)).toEqual(['a','b','z']);expect(exerciseTableRows(exercises,points,{periods:['2026-09'],search:' BENCH   press ',pageSize:1}).items.map(row=>row.id)).toEqual(['b']);});
it('counts only represented periods and actual records, not historical summaries',()=>{const points=[point('1','z','2026-08-01'),point('2','z'),{...point('3','z'),source:'monthly'},point('4','a')];expect(exerciseTableRows(exercises,points,{periods:['2026-09']}).items.find(row=>row.id==='z')?.count).toBe(1);expect(exerciseTableRows(exercises,points,{periods:['2026'],yearly:true}).items[0].count).toBe(2);});
it('sorts before pagination and keeps each exercise grouped across period cells',()=>{const points=[point('1','z'),point('2','z','2026-08-01'),point('3','b')];const first=exerciseTableRows(exercises,points,{periods:['2026-08','2026-09'],pageSize:1}),next=exerciseTableRows(exercises,points,{periods:['2026-08','2026-09'],pageSize:1,page:2});expect(first.items).toEqual([{id:'z',name:'Zulu',count:2}]);expect(next.items[0].id).toBe('b');expect(first.points.filter(point=>point.exerciseId==='z')).toHaveLength(2);});
it('preserves records and achievement data while sorting a filtered population',()=>{const points=[{...point('1','z'),achievement:'weight'},point('2','z','2026-08-01','other'),{...point('3','a'),achievement:'reps'}],before=structuredClone(points);const filtered=points.filter(point=>point.date>='2026-09-01'&&point.locationId==='gym');const result=exerciseTableRows(exercises,filtered,{periods:['2026-09']});expect(result.items.map(row=>[row.id,row.count])).toEqual([['a',1],['z',1],['b',0]]);expect(result.points[0].achievement).toBe('weight');expect(points).toEqual(before);});
