export type StrengthPoint={date:string;weight:number;reps:number;location?:string|null}
export const bestSet=(sets:StrengthPoint[])=>sets.reduce<StrengthPoint|undefined>((best,set)=>!best||set.weight>best.weight||set.weight===best.weight&&set.reps>best.reps?set:best,undefined)
export function strengthGraph(sets:StrengthPoint[]){const hasOneOrTwo=sets.some(s=>s.reps<=2),groups=new Map<string,StrengthPoint[]>();for(const set of sets)(groups.get(set.date)??groups.set(set.date,[]).get(set.date)!).push(set);return[...groups].sort(([a],[b])=>a.localeCompare(b)).map(([date,items])=>hasOneOrTwo?{date,actualOne:bestSet(items.filter(s=>s.reps===1))??null,bestThreePlus:bestSet(items.filter(s=>s.reps>=3))??null}:{date,low:bestSet(items.filter(s=>s.reps>=1&&s.reps<=5))??null,high:bestSet(items.filter(s=>s.reps>=6))??null})}
export function periodBest(sets:StrengthPoint[],period:(date:string)=>string){const groups=new Map<string,StrengthPoint[]>();for(const set of sets)(groups.get(period(set.date))??groups.set(period(set.date),[]).get(period(set.date))!).push(set);return[...groups].map(([key,items])=>({key,best:bestSet(items)!}))}
const meters:Record<string,number>={meters:1,kilometers:1000,miles:1609.344,yards:.9144,feet:.3048}
export const normalizeDistance=(value:number,unit:string,target='miles')=>value*(meters[unit]??1)/(meters[target]??1)
export function runningMetrics(distance:number|undefined,unit:string|undefined,durationSeconds:number|undefined){if(!distance||!durationSeconds||durationSeconds<=0)return null;const miles=normalizeDistance(distance,unit??'miles');return{distanceMiles:miles,speedMph:miles/(durationSeconds/3600),paceSecondsPerMile:durationSeconds/miles}}
export type CardioAggregateInput={date:string;duration:number;distance?:number}
const weekKey=(date:string)=>{const value=new Date(`${date}T00:00:00Z`),day=(value.getUTCDay()+6)%7;value.setUTCDate(value.getUTCDate()-day);return value.toISOString().slice(0,10)}
export function aggregateCardio(items:CardioAggregateInput[],period:'week'|'month'){const groups=new Map<string,CardioAggregateInput[]>();for(const item of items){const key=period==='week'?weekKey(item.date):item.date.slice(0,7);groups.set(key,[...(groups.get(key)??[]),item])}return[...groups].sort(([a],[b])=>a.localeCompare(b)).map(([key,entries])=>{const durationSeconds=entries.reduce((sum,item)=>sum+item.duration,0),distance=entries.reduce((sum,item)=>sum+(item.distance??0),0);return{period:key,durationSeconds,distance,entries:entries.length,averageSpeed:distance>0&&durationSeconds>0?distance/(durationSeconds/3600):null,averagePace:distance>0?durationSeconds/distance:null}})}
