import { localDateKey } from "../strength/logic";
export type Reading = { id:string; measuredAt:string; period:'morning'|'evening'; weight:number; unit:'lb'|'kg'; notes?:string|null }
export const filterReadings=(items:Reading[],start?:string,end?:string,period:'both'|'morning'|'evening'='both')=>items.filter(item=>(!start||localDateKey(item.measuredAt)>=start)&&(!end||localDateKey(item.measuredAt)<=end)&&(period==='both'||item.period===period))
const average=(values:number[])=>values.length?values.reduce((sum,value)=>sum+Number(value),0)/values.length:null
/** One value per calendar day prevents a morning/evening pair from double-weighting that day. */
export function dailyAverages(items:Reading[]){const byDay=new Map<string,number[]>();for(const item of items){const key=localDateKey(item.measuredAt);byDay.set(key,[...(byDay.get(key)??[]),item.weight])}return[...byDay].map(([date,values])=>({date,weight:average(values)!}))}
export type Comparison={start:number;end:number;difference:number;percentage:number;direction:'increase'|'decrease'|'no change';startLabel:string;endLabel:string}|null
export function compareWindows(first:Reading[],last:Reading[],startLabel:string,endLabel:string):Comparison{const start=average(dailyAverages(first).map(item=>item.weight)),end=average(dailyAverages(last).map(item=>item.weight));if(start===null||end===null||start===0)return null;const difference=end-start;return{start,end,difference,percentage:difference/start*100,direction:difference>0?'increase':difference<0?'decrease':'no change',startLabel,endLabel}}
const dateKey=(date:Date)=>date.toISOString().slice(0,10)
const addDays=(date:Date,amount:number)=>{const next=new Date(date);next.setUTCDate(next.getUTCDate()+amount);return next}
function rollingComparison(items:Reading[],days:number,now:Date,previousLabel:string,currentLabel:string){const end=new Date(`${dateKey(now)}T00:00:00.000Z`),currentStart=addDays(end,-(days-1)),previousEnd=addDays(currentStart,-1),previousStart=addDays(previousEnd,-(days-1));return compareWindows(filterReadings(items,dateKey(previousStart),dateKey(previousEnd)),filterReadings(items,dateKey(currentStart),dateKey(end)),previousLabel,currentLabel)}
export const weeklyComparison=(items:Reading[],now=new Date())=>rollingComparison(items,7,now,'Previous 7-day daily average','Rolling 7-day daily average')
export const monthlyComparison=(items:Reading[],now=new Date())=>rollingComparison(items,30,now,'Previous 30-day daily average','Rolling 30-day daily average')
export function customComparison(items:Reading[],start:string,end:string){const selected=filterReadings(items,start,end).sort((a,b)=>Date.parse(a.measuredAt)-Date.parse(b.measuredAt));if(dailyAverages(selected).length<2)return null;const span=(Date.parse(end)-Date.parse(start))/86400000;if(span>=14){const firstEnd=dateKey(addDays(new Date(`${start}T00:00:00.000Z`),6)),lastStart=dateKey(addDays(new Date(`${end}T00:00:00.000Z`),-6));return compareWindows(filterReadings(selected,start,firstEnd),filterReadings(selected,lastStart,end),'First 7-day daily average','Last 7-day daily average')}const days=dailyAverages(selected).sort((a,b)=>a.date.localeCompare(b.date)),first=selected.filter(item=>item.measuredAt.startsWith(days[0].date)),last=selected.filter(item=>item.measuredAt.startsWith(days.at(-1)!.date));return compareWindows(first,last,'Earliest daily average','Latest daily average')}
export function summary(items:Reading[]){if(!items.length)return null;const weights=items.map(item=>item.weight),sorted=[...items].sort((a,b)=>Date.parse(b.measuredAt)-Date.parse(a.measuredAt));return{latestMorning:sorted.find(item=>item.period==='morning')?.weight,latestEvening:sorted.find(item=>item.period==='evening')?.weight,highest:Math.max(...weights),lowest:Math.min(...weights),average:weights.reduce((sum,value)=>sum+Number(value),0)/weights.length,change:sorted[0].weight-sorted[sorted.length-1].weight}}
