import type{SupabaseClient}from'@supabase/supabase-js'
import{dataLoadMessage,relationObject,safeSupabaseDiagnostic}from'../../lib/supabaseError'
import{historyRange,searchPattern,type HistoryFilters,type HistoryPage}from'../../lib/pagedHistory'
export type CardioActivity={id:string;name:string;archived:boolean}
export type CardioSession={id:string;activityId:string;activityName:string;performedAt:string;durationSeconds:number;stepCount?:number;distance?:number;distanceUnit?:string;speed?:number;laps?:number;incline?:number;difficulty?:number;notes?:string;locationId?:string;locationName?:string}
export function cardioLoadMessage(error:unknown,online=true){return dataLoadMessage('Cardio',error,online)}
type CardioSessionRow={id:string;activity_id:string;performed_at:string;duration_seconds:number|null;step_count?:number|null;distance:number|null;distance_unit:string|null;speed:number|null;laps?:number|null;incline:number|null;difficulty:number|null;notes:string|null;location_id:string|null;activity:unknown;location:unknown}
export function parseCardioSessions(rows:CardioSessionRow[]):CardioSession[]{return rows.map(row=>{const activity=relationObject<{name:string}>(row.activity,'cardio_sessions.activity'),location=relationObject<{name:string}>(row.location,'cardio_sessions.location');if(!activity)throw Object.assign(new Error('Cardio session is missing its activity'),{code:'PGRST_CARDINALITY'});return{id:row.id,activityId:row.activity_id,activityName:activity.name,performedAt:row.performed_at,durationSeconds:Number(row.duration_seconds??0),stepCount:row.step_count??undefined,distance:row.distance??undefined,distanceUnit:row.distance_unit??undefined,speed:row.speed??undefined,laps:row.laps??undefined,incline:row.incline??undefined,difficulty:row.difficulty??undefined,notes:row.notes??undefined,locationId:row.location_id??undefined,locationName:location?.name}})}
export async function loadCardio(client:SupabaseClient,userId:string){const{data,error}=await client.from('cardio_activities').select('id,name,archived').eq('user_id',userId).order('name');if(error){safeSupabaseDiagnostic('Cardio','load activities',error);throw error}return{activities:(data??[])as CardioActivity[],sessions:[] as CardioSession[],warning:''}}
export async function saveCardioActivity(client:SupabaseClient,userId:string,name:string,id?:string){const payload={user_id:userId,name:name.trim()};const{error}=id?await client.from('cardio_activities').update(payload).eq('id',id).eq('user_id',userId):await client.from('cardio_activities').insert(payload);if(error)throw error}
export async function archiveCardioActivity(client:SupabaseClient,userId:string,id:string,archived:boolean){const{error}=await client.from('cardio_activities').update({archived}).eq('id',id).eq('user_id',userId);if(error)throw error}
export async function deleteCardioActivity(client:SupabaseClient,userId:string,id:string){const{error}=await client.from('cardio_activities').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export async function saveCardioSession(client:SupabaseClient,userId:string,payload:Record<string,unknown>,id?:string){const row={...payload,user_id:userId};const query=id?client.from('cardio_sessions').update(row).eq('id',id).eq('user_id',userId):client.from('cardio_sessions').insert(row);const{data,error}=await query.select('id').single();if(error)throw error;return data.id as string}
export async function deleteCardioSession(client:SupabaseClient,userId:string,id:string){const{error}=await client.from('cardio_sessions').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export async function getCardioHistoryPage(client:SupabaseClient,userId:string,filters:HistoryFilters):Promise<HistoryPage<CardioSession>>{const range=historyRange(filters.page,filters.pageSize),search=filters.search?.trim();let query=client.from('cardio_sessions').select('id,activity_id,performed_at,duration_seconds,step_count,distance,distance_unit,speed,laps,incline,difficulty,notes,location_id,activity:cardio_activities!cardio_activity_owned_fk!inner(name),location:locations!cardio_location_owned_fk(name)',{count:'exact'}).eq('user_id',userId);if(search)query=query.ilike('activity.name',searchPattern(search));if(filters.activityId)query=query.eq('activity_id',filters.activityId);if(filters.noLocation)query=query.is('location_id',null);else if(filters.locationId)query=query.eq('location_id',filters.locationId);if(filters.start)query=query.gte('performed_at',`${filters.start}T00:00:00`);if(filters.end)query=query.lte('performed_at',`${filters.end}T23:59:59.999`);const{data,error,count}=await query.order('performed_at',{ascending:false}).order('created_at',{ascending:false}).order('id',{ascending:false}).range(range.from,range.to);if(error)throw error;return{items:parseCardioSessions((data??[])as CardioSessionRow[]),total:count??0}}
