import { niceAxis } from "../lib/niceAxis";
/* oxlint-disable react/only-export-components -- axis utilities share the component contract */
import type { Dispatch, SetStateAction, ReactNode } from "react";
import { Select } from "./SelectionControls";

export type XRange = "all" | "12m" | "6m" | "3m" | "custom";
export type AxisSettings = { range:XRange; start:string; end:string; min:string; max:string };
export const defaultAxisSettings:AxisSettings={range:"all",start:"",end:"",min:"",max:""};
export function axisError(settings:AxisSettings){if(settings.range==="custom"&&settings.start&&settings.end&&settings.start>settings.end)return"Start date must not be after end date.";const min=settings.min===""?undefined:Number(settings.min),max=settings.max===""?undefined:Number(settings.max);if(min!==undefined&&!Number.isFinite(min)||max!==undefined&&!Number.isFinite(max))return"Axis bounds must be valid numbers.";if(min!==undefined&&max!==undefined&&min>=max)return"Minimum must be less than maximum.";return""}
export function paddedDomain(values:number[],settings:AxisSettings,minimumStep=0):[number|string,number|string]{if(axisError(settings))return["auto","auto"];const customMin=settings.min===""?undefined:Number(settings.min),customMax=settings.max===""?undefined:Number(settings.max);if(customMin!==undefined||customMax!==undefined)return[customMin??"auto",customMax??"auto"];if(!values.length)return["auto","auto"];return niceAxis(values,minimumStep).domain}
export function rangeDates(settings:AxisSettings,now=new Date()){if(settings.range==="all")return{start:"",end:""};if(settings.range==="custom")return{start:settings.start,end:settings.end};const months=Number(settings.range.slice(0,-1)),from=new Date(now.getFullYear(),now.getMonth()-months,now.getDate()),key=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;return{start:key(from),end:key(now)}}
export function ChartControls({settings,setSettings,unit,showRange=true,children}: {settings:AxisSettings;setSettings:Dispatch<SetStateAction<AxisSettings>>;unit:string;showRange?:boolean;children?:ReactNode}){const error=axisError(settings);return <div className="space-y-2">{showRange&&<Select label="Time period" value={settings.range} options={[{value:"all",label:"All Time"},{value:"12m",label:"Past 12 Months"},{value:"6m",label:"Past 6 Months"},{value:"3m",label:"Past 3 Months"},{value:"custom",label:"Custom Range"}]} onChange={range=>setSettings(current=>({...current,range:range as XRange}))}/>}<details className="chart-controls"><summary>Chart Controls <span>⌄</span></summary><div className="grid gap-3 border-t border-slate-200 p-4 sm:grid-cols-2">{settings.range==="custom"&&<><label className="field-label">Start date<input className="field-input" type="date" value={settings.start} onChange={event=>setSettings(current=>({...current,start:event.target.value}))}/></label><label className="field-label">End date<input className="field-input" type="date" value={settings.end} onChange={event=>setSettings(current=>({...current,end:event.target.value}))}/></label></>}{children}<label className="field-label">Y minimum ({unit})<input className="field-input" type="number" step="any" value={settings.min} onChange={event=>setSettings(current=>({...current,min:event.target.value}))}/></label><label className="field-label">Y maximum ({unit})<input className="field-input" type="number" step="any" value={settings.max} onChange={event=>setSettings(current=>({...current,max:event.target.value}))}/></label><button className="secondary-button" onClick={()=>setSettings(defaultAxisSettings)}>Reset to Auto</button>{error&&<p className="text-sm text-red" role="alert">{error}</p>}</div></details></div>}
