import { useEffect, useEffectEvent, useRef, type ReactNode } from 'react'

export function ConfirmDialog({open,title,description,children,confirmLabel,cancelLabel='Cancel',busy=false,error='',destructive=true,onCancel,onConfirm}:{open:boolean;title:string;description:string;children?:ReactNode;confirmLabel:string;cancelLabel?:string;busy?:boolean;error?:string;destructive?:boolean;onCancel:()=>void;onConfirm:()=>void|Promise<void>}) {
  const cancelRef=useRef<HTMLButtonElement>(null),dialogRef=useRef<HTMLDivElement>(null)
  const cancelFromKeyboard=useEffectEvent(()=>{if(!busy)onCancel()});
  useEffect(()=>{if(!open)return;let active=true;const previous=document.activeElement as HTMLElement|null;queueMicrotask(()=>{if(active)cancelRef.current?.focus()});const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();cancelFromKeyboard()}if(event.key==='Tab'){const focusable=[...(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')??[])];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{active=false;document.removeEventListener('keydown',key);previous?.focus()}},[open])
  if(!open)return null
  const working=confirmLabel.startsWith('Delete')?'Deleting…':confirmLabel.startsWith('Roll Back')?'Rolling back…':'Working...'
  return <div className="dialog-overlay" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onCancel()}}><div ref={dialogRef} className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-description"><div className={`dialog-icon ${destructive?'dialog-icon-danger':''}`} aria-hidden="true">⌫</div><h2 id="confirm-title" className="font-display text-xl font-black text-ink">{title}</h2><p id="confirm-description" className="mt-2 text-sm leading-relaxed text-slate-500">{description}</p>{children&&<div className="dialog-summary">{children}</div>}{error&&<p className="mt-3 text-sm text-red" role="alert">{error}</p>}<div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button ref={cancelRef} className="secondary-button" disabled={busy} onClick={onCancel}>{cancelLabel}</button><button className={destructive?'danger-button':'primary-button'} disabled={busy} onClick={()=>void onConfirm()}>{busy?working:confirmLabel}</button></div></div></div>
}
