import {useState,type FormEvent} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {passwordError,requestPasswordReset,recoveryView} from '../lib/passwordRecovery';
export function ForgotPassword({client,onBack}:{client:SupabaseClient;onBack:()=>void}){
 const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;setBusy(true);setMessage(await requestPasswordReset(client,email,location.origin));setBusy(false);};
 return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">PROGRESSIVE OVERLOAD</p><h1 className="page-title">Forgot Password</h1><p className="mt-3 text-sm">Enter your email to request a password reset link.</p><form className="auth-form" onSubmit={submit} aria-busy={busy}><label className="auth-label">Email<input className="auth-input" type="email" autoComplete="email" required disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="auth-submit" disabled={busy}>{busy?'Requesting link?':'Send reset link'}</button></form>{message&&<p className="auth-message auth-message-success" role="status">{message} If nothing arrives, try again later.</p>}<button className="secondary-button mt-4" disabled={busy} onClick={onBack}>Back to sign in</button></section></main>;
}
export function PasswordForm({client,recovery=false,onDone}:{client:SupabaseClient;recovery?:boolean;onDone:()=>void}){
 const [password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[current,setCurrent]=useState(''),[nonce,setNonce]=useState(''),[reauth,setReauth]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false),[notice,setNotice]=useState('');
 const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;if(password.length<8||password!==repeat){setError('Use at least 8 characters and matching passwords.');return;}setBusy(true);setError('');try{const {error}=await client.auth.updateUser({password,...(!recovery?{current_password:current}:{}),...(nonce?{nonce}: {})});if(error){setError(passwordError(error.code));if(error.code?.startsWith('reauthentication'))setReauth(true);}else{setPassword('');setRepeat('');setCurrent('');setNonce('');setSuccess(true);}}catch{setError('Could not change your password. Check your connection and retry.');}finally{setBusy(false);}};
 if(success)return <div><p role="status" className="auth-message auth-message-success">Your password has been changed.</p><button className="primary-button mt-4" onClick={onDone}>{recovery?'Continue to app':'Done'}</button></div>;
 return <form className="auth-form" onSubmit={submit} aria-busy={busy}>
 {!recovery&&<label className="auth-label">Current password<input type="password" className="auth-input" autoComplete="current-password" required disabled={busy} value={current} onChange={e=>setCurrent(e.target.value)}/></label>}
 <label className="auth-label">New password<input type="password" className="auth-input" autoComplete="new-password" required minLength={8} disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/><small>Use at least 8 characters.</small></label>
 <label className="auth-label">Confirm new password<input type="password" className="auth-input" autoComplete="new-password" required minLength={8} disabled={busy} value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>
 {reauth&&<><button type="button" className="secondary-button" disabled={busy} onClick={async()=>{setBusy(true);try{const {error}=await client.auth.reauthenticate();setNotice(error?'Could not send verification. Try again later.':'Check your email for a verification code.');}catch{setNotice('Could not send verification. Check your connection.');}finally{setBusy(false);}}}>Send verification code</button><label className="auth-label">Email verification code<input className="auth-input" autoComplete="one-time-code" value={nonce} disabled={busy} onChange={e=>setNonce(e.target.value)}/></label></>}
 {notice&&<p role="status">{notice}</p>}{error&&<p className="auth-message auth-message-error" role="alert">{error}</p>}
 <button className="auth-submit" disabled={busy}>{busy?'Saving password?':'Save new password'}</button><button type="button" className="secondary-button" disabled={busy} onClick={onDone}>Cancel</button>
 </form>;
}
export function RecoveryScreen({client,loading,hasSession,invalid,email,error,retry}:{client:SupabaseClient;loading:boolean;hasSession:boolean;invalid:boolean;email?:string;error?:string;retry:()=>void}){
 const view=recoveryView(loading,hasSession,invalid),[request,setRequest]=useState(false);
 const exit=()=>location.replace('/');
 if(request)return <ForgotPassword client={client} onBack={exit}/>;
 return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">PROGRESSIVE OVERLOAD</p><h1 className="page-title">Set New Password</h1>{view==='loading'?<div role="status" className="mt-4">Checking recovery session?{error&&<><p role="alert">Could not verify the recovery session. Check your connection.</p><button className="secondary-button mt-3" onClick={retry}>Retry</button></>}</div>:view==='invalid'?<div className="mt-4"><p role="alert">This recovery link is invalid, expired, or already used. Request a fresh link and open the newest email while online.</p><button className="primary-button mt-4" onClick={()=>setRequest(true)}>Request a new link</button><button className="secondary-button mt-3" onClick={exit}>Back to sign in</button></div>:<><p className="mt-3 text-sm">Choose a new password for {email??'your account'}.</p><PasswordForm client={client} recovery onDone={exit}/></>}</section></main>;
}
