import type { DistanceUnit, Exercise, Location, Workout, WorkoutDraft } from './types'
import { isRepsOnlyExercise } from './logic'
import { parseDecimal, parseWhole } from '../../lib/numeric'
export type QuickLiftSet={key?:string;id?:string;notes?:string;weight:string;reps:string}
export type QuickLiftDraft={id?:string;original?:Workout;date:string;locationId:string|null;exercise:Exercise|null;sets:QuickLiftSet[];weight:string;reps:string;load:string;distance:string;distanceUnit:DistanceUnit;laps:string;durationSeconds:string}
export type QuickLiftErrors=Partial<Record<'exercise'|'weight'|'reps'|'date'|'load'|'distance'|'laps'|'duration'|'save',string>>
export function localToday(now=new Date()){return`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}
export const newQuickLiftSet=(weight='',reps='',key:string=crypto.randomUUID()):QuickLiftSet=>({key,weight,reps})
export function newQuickLift(locations:Location[],date=localToday(),locationId?:string|null):QuickLiftDraft{return{date,locationId:locationId===undefined?locations.find(x=>x.isDefault&&!x.archived)?.id??null:locationId,exercise:null,sets:[newQuickLiftSet()],weight:'',reps:'',load:'',distance:'',distanceUnit:'meters',laps:'1',durationSeconds:''}}
export function validateQuickLift(draft:QuickLiftDraft){const errors:QuickLiftErrors={};if(!draft.exercise)errors.exercise='Choose an exercise.';if(!draft.date)errors.date='Choose a date.';if(draft.exercise?.trackingType==='repetitions'){const repsOnly=isRepsOnlyExercise(draft.exercise),sets=draft.sets.length===1&&draft.sets[0].weight===''&&draft.weight!==''?[{weight:draft.weight,reps:draft.reps}]:draft.sets;if(!sets.length)errors.reps='Add at least one set.';sets.forEach((set,i)=>{const weight=Number(set.weight),reps=Number(set.reps);if(!repsOnly&&(set.weight===''||!Number.isFinite(weight)||weight<0))errors.weight=`Set ${i+1}: weight must be zero or more.`;if(set.reps===''||!Number.isInteger(reps)||reps<1)errors.reps=`Set ${i+1}: reps must be a positive whole number.`})}if(draft.exercise?.trackingType==='distance'){const load=Number(draft.load),distance=Number(draft.distance),laps=Number(draft.laps),duration=draft.durationSeconds===''?undefined:Number(draft.durationSeconds);if(draft.load===''||!Number.isFinite(load)||load<0)errors.load='Load must be zero or more.';if(draft.distance===''||!Number.isFinite(distance)||distance<=0)errors.distance='Distance must be greater than zero.';if(draft.laps===''||!Number.isInteger(laps)||laps<1)errors.laps='Laps must be a positive whole number.';if(duration!==undefined&&(!Number.isFinite(duration)||duration<0))errors.duration='Duration cannot be negative.'}return errors}
export function quickLiftToWorkout(draft:QuickLiftDraft):WorkoutDraft{if(!draft.exercise)throw new Error('Choose an exercise.');const inputSets=draft.sets.length===1&&draft.sets[0].weight===''&&draft.weight!==''?[{weight:draft.weight,reps:draft.reps}]:draft.sets,repsOnly=isRepsOnlyExercise(draft.exercise);const sets=draft.exercise.trackingType==='repetitions'?inputSets.map((set,index)=>({id:draft.sets[index]?.id,notes:draft.sets[index]?.notes,exerciseId:draft.exercise!.id,setOrder:index+1,trackingType:'repetitions' as const,weight:repsOnly?undefined:parseDecimal(set.weight,'Weight',{allowZero:true}),reps:parseWhole(set.reps,'Reps')})):[{id:draft.original?.sets[0]?.id,notes:draft.original?.sets[0]?.notes,exerciseId:draft.exercise.id,setOrder:1,trackingType:'distance' as const,load:parseDecimal(draft.load,'Load',{allowZero:true}),distance:parseDecimal(draft.distance,'Distance'),distanceUnit:draft.distanceUnit,laps:parseWhole(draft.laps,'Laps'),durationSeconds:parseWhole(draft.durationSeconds,'Duration',{optional:true})}];return{id:draft.id,originalPerformedAt:draft.original?.performedAt,date:draft.date,locationId:draft.locationId,notes:draft.original?.notes??'',durationSeconds:draft.original?.durationSeconds??undefined,exercises:[{key:'quick-lift',exercise:draft.exercise,sets}]}}
export function isQuickWorkout(workout:Workout){return new Set(workout.sets.map(s=>s.exercise.id)).size===1}
export function quickLiftFromWorkout(workout:Workout):QuickLiftDraft{const set=workout.sets[0],date=new Date(workout.performedAt),localDate=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,base=newQuickLift([],localDate,workout.location?.id??null);return{...base,original:workout,id:workout.id,exercise:set.exercise,sets:workout.sets.map(s=>({...newQuickLiftSet(s.weight===undefined?'':String(s.weight),s.reps===undefined?'':String(s.reps),s.id??crypto.randomUUID()),id:s.id,notes:s.notes})),weight:set.weight===undefined?'':String(set.weight),reps:set.reps===undefined?'':String(set.reps),load:set.load===undefined?'':String(set.load),distance:set.distance===undefined?'':String(set.distance),distanceUnit:set.distanceUnit??'meters',laps:set.laps===undefined?'1':String(set.laps),durationSeconds:set.durationSeconds===undefined?'':String(set.durationSeconds)}}
