import type { SupabaseClient } from '@supabase/supabase-js'
import { localDateKey, localDateToIso, orderedSets } from './logic'
import type { Exercise, Location, MuscleGroup, StrengthSet, TrackingType, Workout, WorkoutDraft } from './types'
import { dataLoadMessage, relationObject, safeSupabaseDiagnostic } from '../../lib/supabaseError'
import { historyRange, searchPattern, type HistoryFilters, type HistoryPage } from '../../lib/pagedHistory'

type ExerciseRow={id:string;user_id:string;name:string;tracking_type:TrackingType;load_mode?:'weight_reps'|'reps_only';major_muscle_group:MuscleGroup;is_compound:boolean;archived:boolean;created_at:string;updated_at:string}
type AssignmentRow={exercise_id:string;muscle_tag:string}
type GroupAssignmentRow={exercise_id:string;major_group:MuscleGroup}
export async function getExercises(client:SupabaseClient,userId:string):Promise<Exercise[]>{
  const [{data:rows,error},{data:tags,error:tagError},{data:groups,error:groupError}]=await Promise.all([
    client.from('exercises').select('*').eq('user_id',userId).order('name'),
    client.from('exercise_muscle_assignments').select('exercise_id,muscle_tag').eq('user_id',userId),
    client.from('exercise_group_assignments').select('exercise_id,major_group').eq('user_id',userId),
  ]);if(error){safeSupabaseDiagnostic('Strength','load exercises',error);throw error}if(tagError){safeSupabaseDiagnostic('Strength','load muscle assignments',tagError);throw tagError}if(groupError){safeSupabaseDiagnostic('Strength','load group assignments',groupError);throw groupError}
  const{data:uses,error:useError}=await client.from('strength_sets').select('exercise_id,weight,reps,workout:strength_workouts!strength_set_workout_owned_fk(performed_at)').eq('user_id',userId);if(useError)safeSupabaseDiagnostic('Strength','load optional exercise usage',useError)
  const assignments=(tags??[]) as AssignmentRow[],groupAssignments=(groups??[]) as GroupAssignmentRow[];const usage=new Map<string,{count:number;recent:string|null;pr?:number;lastWeight?:number;lastReps?:number}>();for(const row of (uses??[]) as {exercise_id:string;weight:number|null;reps:number|null;workout:unknown}[]){const workout=relationObject<{performed_at:string}>(row.workout,'strength_sets.workout');if(!workout)continue;const value=usage.get(row.exercise_id)??{count:0,recent:null};value.count++;if(row.weight!=null)value.pr=Math.max(value.pr??-Infinity,row.weight);const day=workout.performed_at.slice(0,10),recent=value.recent?.slice(0,10);if(!recent||day>recent||(day===recent&&row.weight!=null&&(row.weight>(value.lastWeight??-Infinity)||row.weight===value.lastWeight&&(row.reps??0)>(value.lastReps??0)))){value.recent=workout.performed_at;value.lastWeight=row.weight??undefined;value.lastReps=row.reps??undefined}usage.set(row.exercise_id,value)}
  return ((rows??[]) as ExerciseRow[]).map(row=>{const assignedGroups=groupAssignments.filter(a=>a.exercise_id===row.id).map(a=>a.major_group),u=usage.get(row.id);return{id:row.id,userId:row.user_id,name:row.name,trackingType:row.tracking_type,loadMode:row.load_mode??'weight_reps',majorMuscleGroups:assignedGroups.length?assignedGroups:[row.major_muscle_group],muscleTags:assignments.filter(a=>a.exercise_id===row.id).map(a=>a.muscle_tag),isCompound:row.is_compound,archived:row.archived,createdAt:row.created_at,updatedAt:row.updated_at,usageCount:u?.count??0,lastUsedAt:u?.recent??null,prWeight:u?.pr,lastWeight:u?.lastWeight,lastReps:u?.lastReps}})
}
export type ExerciseInput={name:string;trackingType:TrackingType;loadMode:'weight_reps'|'reps_only';majorMuscleGroups:MuscleGroup[];muscleTags:string[];isCompound:boolean}
export async function saveExercise(client:SupabaseClient,userId:string,input:ExerciseInput,id?:string){const{data,error}=await client.rpc('save_strength_exercise',{p_exercise:{id:id??null,user_id:userId,name:input.name.trim().replace(/\s+/g,' '),tracking_type:input.trackingType,load_mode:input.trackingType==='distance'?'weight_reps':input.loadMode,major_muscle_group:input.majorMuscleGroups[0],major_muscle_groups:input.majorMuscleGroups,is_compound:input.isCompound},p_muscle_tags:input.muscleTags});if(error)throw error;return data as string}
export async function deleteUnusedExercise(client:SupabaseClient,userId:string,id:string){const{error}=await client.from('exercises').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export async function setExerciseArchived(client:SupabaseClient,userId:string,id:string,archived:boolean){const{error}=await client.from('exercises').update({archived}).eq('id',id).eq('user_id',userId);if(error)throw error}
export async function getLocations(client:SupabaseClient,userId:string):Promise<Location[]>{const{data,error}=await client.from('locations').select('id,name,is_default,archived').eq('user_id',userId).order('name');if(error){safeSupabaseDiagnostic('Strength','load locations',error);throw error}return (data??[]).map(row=>({id:row.id,name:row.name,isDefault:row.is_default,archived:row.archived}))}
export async function saveLocation(client:SupabaseClient,userId:string,name:string,id?:string){
 const normalized=name.trim().replace(/\s+/g,' ');
 const locations=await getLocations(client,userId);
 if(!normalized||locations.some(location=>location.id!==id&&location.name.trim().replace(/\s+/g,' ').toLocaleLowerCase()===normalized.toLocaleLowerCase()))throw new Error('Use a unique location name.');
 const payload={user_id:userId,name:normalized};const query=id?client.from('locations').update(payload).eq('id',id).eq('user_id',userId):client.from('locations').insert(payload);const{data,error}=await query.select('id').single();if(error)throw error;return data.id as string;
}
export async function deleteLocation(client:SupabaseClient,userId:string,id:string){const{error}=await client.from('locations').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export async function setLocationArchived(client:SupabaseClient,userId:string,id:string,archived:boolean){const{error}=await client.from('locations').update({archived,is_default:false}).eq('id',id).eq('user_id',userId);if(error)throw error}
export async function setDefaultLocation(client:SupabaseClient,_userId:string,id:string){const{error}=await client.rpc('set_default_location',{p_location_id:id});if(error)throw error}

type SetRow={id:string;exercise_id:string;set_order:number;tracking_type:TrackingType;weight:number|null;reps:number|null;load:number|null;distance:number|null;distance_unit:StrengthSet['distanceUnit']|null;laps:number|null;duration_seconds:number|null;notes:string|null;exercise:unknown}
type WorkoutRow={id:string;performed_at:string;created_at?:string;duration_seconds:number|null;notes:string|null;location:unknown;sets:unknown}
export function parseWorkoutRows(rows:WorkoutRow[]):Workout[]{return rows.map(w=>{const location=relationObject<{id:string;name:string;is_default:boolean;archived:boolean}>(w.location,'strength_workouts.location');if(!Array.isArray(w.sets))throw Object.assign(new Error('Unexpected cardinality for strength_workouts.sets'),{code:'PGRST_CARDINALITY'});return{id:w.id,performedAt:w.performed_at,createdAt:w.created_at,durationSeconds:w.duration_seconds,notes:w.notes,location:location?{id:location.id,name:location.name,isDefault:location.is_default,archived:location.archived}:null,sets:(w.sets as SetRow[]).sort((a,b)=>a.set_order-b.set_order).map(s=>{const exercise=relationObject<ExerciseRow>(s.exercise,'strength_sets.exercise');if(!exercise)throw Object.assign(new Error('Strength set is missing its exercise'),{code:'PGRST_CARDINALITY'});return{id:s.id,exerciseId:s.exercise_id,setOrder:s.set_order,trackingType:s.tracking_type,weight:s.weight??undefined,reps:s.reps??undefined,load:s.load??undefined,distance:s.distance??undefined,distanceUnit:s.distance_unit??undefined,laps:s.laps??undefined,durationSeconds:s.duration_seconds??undefined,notes:s.notes??undefined,exercise:{id:exercise.id,userId:exercise.user_id,name:exercise.name,trackingType:exercise.tracking_type,majorMuscleGroups:[exercise.major_muscle_group],muscleTags:[],isCompound:exercise.is_compound,archived:exercise.archived,createdAt:exercise.created_at,updatedAt:exercise.updated_at,usageCount:0,lastUsedAt:null}}})}})}
export async function getWorkouts(client:SupabaseClient,userId:string,from?:string):Promise<Workout[]>{let query=client.from('strength_workouts').select('id,performed_at,created_at,duration_seconds,notes,location:locations!strength_workout_location_owned_fk(id,name,is_default,archived),sets:strength_sets!strength_set_workout_owned_fk(id,exercise_id,set_order,tracking_type,weight,reps,load,distance,distance_unit,laps,duration_seconds,notes,exercise:exercises!strength_set_exercise_type_owned_fk(*))').eq('user_id',userId).order('performed_at',{ascending:false}).order('created_at',{ascending:false}).order('id',{ascending:false}).range(0,19);if(from)query=query.gte('performed_at',from);const{data,error}=await query;if(error){safeSupabaseDiagnostic('Strength','load workouts',error);throw error}return parseWorkoutRows((data??[]) as WorkoutRow[])}
export async function getWorkoutById(client:SupabaseClient,userId:string,id:string){const{data,error}=await client.from('strength_workouts').select('id,performed_at,created_at,duration_seconds,notes,location:locations!strength_workout_location_owned_fk(id,name,is_default,archived),sets:strength_sets!strength_set_workout_owned_fk(id,exercise_id,set_order,tracking_type,weight,reps,load,distance,distance_unit,laps,duration_seconds,notes,exercise:exercises!strength_set_exercise_type_owned_fk(*))').eq('user_id',userId).eq('id',id).single();if(error)throw error;return parseWorkoutRows([data as WorkoutRow])[0]}
const setPayload=(userId:string,workoutId:string,set:StrengthSet)=>({user_id:userId,workout_id:workoutId,exercise_id:set.exerciseId,set_order:set.setOrder,tracking_type:set.trackingType,weight:set.trackingType==='repetitions'?set.weight:null,reps:set.trackingType==='repetitions'?set.reps:null,load:set.trackingType==='distance'?set.load:null,distance:set.trackingType==='distance'?set.distance:null,distance_unit:set.trackingType==='distance'?set.distanceUnit:null,laps:set.trackingType==='distance'?set.laps:null,duration_seconds:set.trackingType==='distance'?set.durationSeconds:null,notes:set.notes?.trim()||null})
export async function saveWorkout(client:SupabaseClient,userId:string,draft:WorkoutDraft){const performed_at=draft.originalPerformedAt&&localDateKey(draft.originalPerformedAt)===draft.date?draft.originalPerformedAt:localDateToIso(draft.date);const sets=orderedSets(draft).map(set=>({...setPayload(userId,draft.id??'',set),id:set.id??null}));const{data,error}=await client.rpc('save_strength_workout',{p_workout:{id:draft.id??null,performed_at,location_id:draft.locationId||null,notes:draft.notes.trim()||null,duration_seconds:draft.durationSeconds??null},p_sets:sets});if(error)throw error;return data as string}
export async function deleteWorkout(client:SupabaseClient,userId:string,id:string){const{error}=await client.from('strength_workouts').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export async function getHistoricalEvidence(client:SupabaseClient,userId:string){const{data,error}=await client.from('historical_strength_records').select('id,exercise_id,period_start,tracking_type,weight,reps,load,distance,distance_unit,laps,duration_seconds').eq('user_id',userId);if(error){safeSupabaseDiagnostic('Strength','load historical records',error);throw error}return (data??[]).map(row=>({id:`historical:${row.id}`,exerciseId:row.exercise_id,setOrder:0,performedAt:`${row.period_start}T00:00:00`,trackingType:row.tracking_type as TrackingType,weight:row.weight??undefined,reps:row.reps??undefined,load:row.load??undefined,distance:row.distance??undefined,distanceUnit:row.distance_unit??undefined,laps:row.laps??undefined,durationSeconds:row.duration_seconds??undefined}))}
export function strengthLoadMessage(error:unknown){return dataLoadMessage('Strength',error,typeof navigator==='undefined'||navigator.onLine)}
export async function getStrengthHistoryPage(client:SupabaseClient,userId:string,filters:HistoryFilters):Promise<HistoryPage<Workout>>{const range=historyRange(filters.page,filters.pageSize),search=filters.search?.trim();let ids=client.from('strength_workouts').select(search?'id,sets:strength_sets!strength_set_workout_owned_fk!inner(exercise_id,exercise:exercises!strength_set_exercise_type_owned_fk!inner(name))':'id,sets:strength_sets!strength_set_workout_owned_fk(exercise_id)',{count:'exact'}).eq('user_id',userId);if(search)ids=ids.ilike('sets.exercise.name',searchPattern(search));if(filters.exerciseId)ids=ids.eq('sets.exercise_id',filters.exerciseId);if(filters.noLocation)ids=ids.is('location_id',null);else if(filters.locationId)ids=ids.eq('location_id',filters.locationId);if(filters.start)ids=ids.gte('performed_at',`${filters.start}T00:00:00`);if(filters.end)ids=ids.lte('performed_at',`${filters.end}T23:59:59.999`);const pageResult=await ids.order('performed_at',{ascending:false}).order('created_at',{ascending:false}).order('id',{ascending:false}).range(range.from,range.to);if(pageResult.error)throw pageResult.error;const pageIds=(pageResult.data??[]).map(row=>row.id);if(!pageIds.length)return{items:[],total:pageResult.count??0};const{data,error}=await client.from('strength_workouts').select('id,performed_at,created_at,duration_seconds,notes,location:locations!strength_workout_location_owned_fk(id,name,is_default,archived),sets:strength_sets!strength_set_workout_owned_fk(id,exercise_id,set_order,tracking_type,weight,reps,load,distance,distance_unit,laps,duration_seconds,notes,exercise:exercises!strength_set_exercise_type_owned_fk(*))').eq('user_id',userId).in('id',pageIds);if(error)throw error;const parsed=parseWorkoutRows((data??[])as WorkoutRow[]),byId=new Map(parsed.map(item=>[item.id,item]));return{items:pageIds.flatMap(id=>byId.get(id)?[byId.get(id)!]:[]),total:pageResult.count??0}}
