import{describe,expect,it}from'vitest';import sql from '../../../supabase/migrations/202608310005_private_stretches_and_sets.sql?raw';import{starterStretches}from'./starterLibrary'
describe('stretch migration 005 repair',()=>{
 it('establishes the composite key before mobility_sets',()=>{const key=sql.indexOf('mobility_sessions_id_user_unique unique(id,user_id)'),table=sql.indexOf('create table if not exists public.mobility_sets');expect(key).toBeGreaterThan(-1);expect(key).toBeLessThan(table)})
 it('supports clean and partial execution paths',()=>{expect(sql).toContain('add column if not exists tracking_type');expect(sql).toContain('Existing mobility_activities.tracking_type is incompatible');expect(sql).toContain('Existing mobility_activities_tracking_type_check is incompatible');expect(sql).toContain('create table if not exists public.mobility_sets')})
 it('preflights normalized duplicates and validates a prior index',()=>{expect(sql).toContain('Normalized duplicate stretch names must be renamed manually');expect(sql).toContain('Existing mobility_activities_user_normalized_name_unique is incompatible')})
 it('validates a named composite constraint and accepts an equivalent constraint',()=>{expect(sql).toContain('Existing mobility_sessions_id_user_unique is incompatible');expect(sql).toContain("c.contype in('p','u')");expect(sql).toContain("array['id','user_id']")})
 it('casts both catalog name arrays to text arrays',()=>{expect(sql.match(/array_agg\(a\.attname::text order by k\.ordinality\)/g)).toHaveLength(2);expect(sql.match(/array\['id','user_id'\]::text\[\]/g)).toHaveLength(2);expect(sql).not.toMatch(/array_agg\(a\.attname order/)})
 it('targets authenticated users with four set policies',()=>{for(const action of['select','insert','update','delete'])expect(sql).toMatch(new RegExp(`create policy mobility_sets_${action}_own[^;]+for ${action} to authenticated`));expect(sql).toContain('(select auth.uid())=user_id')})
 it('uses a same-user foreign key and validates resumed tables',()=>{expect(sql).toContain('foreign key(session_id,user_id) references public.mobility_sessions(id,user_id)');expect(sql).toContain('Existing public.mobility_sets is incompatible')})
 it('does not expose the arbitrary-user security definer installer',()=>{expect(sql).toContain('security definer');for(const role of['public','anon','authenticated'])expect(sql).toContain(`revoke all on function public.install_private_stretch_library(uuid) from ${role}`);expect(sql).not.toContain('grant execute on function public.install_private_stretch_library')})
 it('keeps the account-scoped saver available',()=>{expect(sql).toContain('grant execute on function public.save_stretch_entry(jsonb,jsonb) to authenticated');expect(sql).toContain('where id=activity and user_id=uid');expect(sql).toContain('where id=sid and user_id=uid')})
 it('validates typed positive whole-number values before writing sequential sets',()=>{expect(sql).toContain("!~'^[1-9][0-9]*$'");expect(sql).toContain("item ? 'duration_seconds'");expect(sql).toContain("item ? 'reps'");expect(sql).toContain('ord:=ord+1')})
 it('keeps 25 defaults, idempotent installation, trigger install, and legacy backfill',()=>{expect(starterStretches).toHaveLength(25);expect(sql).toContain('version>=1');expect(sql).toContain('on conflict(user_id)');expect(sql).toContain('after insert on auth.users');expect(sql).toContain('generate_series(1,set_count)')})
})
