import type{SupabaseClient}from'@supabase/supabase-js';import{dataLoadMessage,relationObject,safeSupabaseDiagnostic}from'../../lib/supabaseError'
import{historyRange,searchPattern,type HistoryFilters,type HistoryPage}from'../../lib/pagedHistory'
export type FlexTracking='time'|'reps';export type FlexSet={id?:string;setOrder:number;durationSeconds?:number;reps?:number};export type FlexActivity={id:string;name:string;trackingType:FlexTracking;archived:boolean;areas:string[]};export type FlexEntry={id:string;activityId:string;activityName:string;trackingType:FlexTracking;areas:string[];performedAt:string;sets:FlexSet[];notes?:string}
export const flexibilityLoadMessage=(error:unknown,online=true)=>dataLoadMessage('Flexibility',error,online)
type EntryRow={id:string;activity_id:string;performed_at:string;duration_seconds:number|null;set_count:number;notes:string|null;activity:unknown;sets?:unknown}
export function parseFlexEntries(rows:EntryRow[],activityAreas:(id:string)=>string[]):FlexEntry[]{return rows.map(row=>{const activity=relationObject<{name:string;tracking_type:FlexTracking}>(row.activity,'mobility_sessions.activity');if(!activity)throw Object.assign(new Error('Stretch entry is missing its activity'),{code:'PGRST_CARDINALITY'});const related=Array.isArray(row.sets)?row.sets as{id:string;set_order:number;duration_seconds:number|null;reps:number|null}[]:[],sets=related.length?related.sort((a,b)=>a.set_order-b.set_order).map(s=>({id:s.id,setOrder:s.set_order,durationSeconds:s.duration_seconds??undefined,reps:s.reps??undefined})):Array.from({length:row.set_count},(_,i)=>({setOrder:i+1,durationSeconds:row.duration_seconds??undefined}));return{id:row.id,activityId:row.activity_id,activityName:activity.name,trackingType:activity.tracking_type??'time',areas:activityAreas(row.activity_id),performedAt:row.performed_at,sets,notes:row.notes??undefined}})}
export async function loadFlexibility(client:SupabaseClient,userId:string){const{data:a,error:ae}=await client.from('mobility_activities').select('id,name,tracking_type,archived').eq('user_id',userId).order('name');if(ae){safeSupabaseDiagnostic('Flexibility','load activities',ae);throw ae}const{data:areas,error}=await client.from('mobility_activity_area_assignments').select('activity_id,body_area').eq('user_id',userId);if(error)safeSupabaseDiagnostic('Flexibility','load body areas',error);const rows=areas??[],activityAreas=(id:string)=>rows.filter(x=>x.activity_id===id).map(x=>x.body_area);return{activities:(a??[]).map(x=>({id:x.id,name:x.name,trackingType:(x.tracking_type??'time')as FlexTracking,archived:x.archived,areas:activityAreas(x.id)})),entries:[]as FlexEntry[],warning:error?dataLoadMessage('Flexibility body areas',error,typeof navigator==='undefined'||navigator.onLine):''}}
export async function saveFlexActivity(client:SupabaseClient,name:string,trackingType:FlexTracking,areas:string[],id?:string){const{data,error}=await client.rpc('save_flexibility_activity',{p_activity:{id:id??null,name:name.trim(),tracking_type:trackingType},p_areas:areas});if(error)throw error;return data as string}
export async function archiveFlexActivity(client:SupabaseClient,userId:string,id:string,archived:boolean){const{error}=await client.from('mobility_activities').update({archived}).eq('id',id).eq('user_id',userId);if(error)throw error}
export async function deleteFlexActivity(client:SupabaseClient,userId:string,id:string){const{error}=await client.from('mobility_activities').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export async function saveFlexEntry(client:SupabaseClient,entry:{id?:string;activityId:string;performedAt:string;notes:string},tracking:FlexTracking,sets:FlexSet[]){const pSets=sets.map(s=>tracking==='time'?{duration_seconds:s.durationSeconds}:{reps:s.reps}),{data,error}=await client.rpc('save_stretch_entry',{p_entry:{id:entry.id??null,activity_id:entry.activityId,performed_at:entry.performedAt,notes:entry.notes||null},p_sets:pSets});if(error)throw error;return data as string}
export async function deleteFlexEntry(client:SupabaseClient,userId:string,id:string){const{error}=await client.from('mobility_sessions').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export const parseFlexSessions=parseFlexEntries
export async function getFlexHistoryPage(client:SupabaseClient,userId:string,filters:HistoryFilters):Promise<HistoryPage<FlexEntry>>{const range=historyRange(filters.page,filters.pageSize),search=filters.search?.trim();let query=client.from('mobility_sessions').select('id,activity_id,performed_at,duration_seconds,set_count,notes,activity:mobility_activities!mobility_activity_owned_fk!inner(name,tracking_type,areas:mobility_activity_area_assignments!mobility_area_owned_fk(body_area)),sets:mobility_sets!mobility_sets_session_owned_fk(id,set_order,duration_seconds,reps)',{count:'exact'}).eq('user_id',userId);if(search)query=query.ilike('activity.name',searchPattern(search));if(filters.activityId)query=query.eq('activity_id',filters.activityId);if(filters.trackingType)query=query.eq('activity.tracking_type',filters.trackingType);if(filters.bodyArea)query=query.eq('activity.areas.body_area',filters.bodyArea);if(filters.start)query=query.gte('performed_at',`${filters.start}T00:00:00`);if(filters.end)query=query.lte('performed_at',`${filters.end}T23:59:59.999`);const{data,error,count}=await query.order('performed_at',{ascending:false}).order('created_at',{ascending:false}).order('id',{ascending:false}).range(range.from,range.to);if(error)throw error;const rows=(data??[])as(EntryRow&{activity:{areas?:{body_area:string}[]}})[],areas=(id:string)=>rows.find(row=>row.activity_id===id)?.activity?.areas?.map(item=>item.body_area)??[];return{items:parseFlexEntries(rows,areas),total:count??0}}
