import {subscribePrivacyChange} from './privacy';
import { useCallback,useEffect,useRef,useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer } from 'recharts';
import { Select } from '../../components/SelectionControls';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { formatMetric } from '../../lib/metricTicks';
import { createGroup,joinGroup,listGroups,loadGroupSummary,manageGroup,getGroupCode,replaceGroupCode,groupError,type Group,type GroupSummary } from './repository';
import { cardioRanks,groupPeriods,muscleCategories,strengthRanks } from './logic';
import {copyGroupCode,displayGroupCode,shareGroupCode} from './groupCode';
const colors=['#b91c1c','#15803d','#1d4ed8','#18181b','#c2410c','#7e22ce','#0f766e'];
export function GroupsFeature(props:{client:SupabaseClient;userId:string}){return <GroupScreen key={props.userId} {...props}/>;}
function GroupScreen({client,userId}:{client:SupabaseClient;userId:string}){
 const [groups,setGroups]=useState<Group[]>([]),[selected,setSelected]=useState(''),[period,setPeriod]=useState('month'),[tab,setTab]=useState<'strength'|'cardio'>('strength'),[activity,setActivity]=useState(''),[metric,setMetric]=useState<'duration'|'distance'>('duration');
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[snapshot,setSnapshot]=useState<{key:string;data:GroupSummary}|null>(null);
 const [dialog,setDialog]=useState<{kind:string;memberId?:string;label?:string}|null>(null),[name,setName]=useState(''),[displayName,setDisplayName]=useState(''),[code,setCode]=useState(''),[consent,setConsent]=useState(false),[codeSnapshot,setCodeSnapshot]=useState<{groupId:string;code:string}|null>(null),[codeError,setCodeError]=useState(''),[notice,setNotice]=useState(''),[hidden,setHidden]=useState<string[]>([]);
 const creationRequest=useRef('');
 const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',groupId=selected||groups[0]?.id||'',key=`${userId}:${groupId}:${period}:${activity}:${revision}`,data=snapshot?.key===key?snapshot.data:null,owner=data?.members.some(member=>member.is_self&&member.role==='owner');
 const displayedCode=codeSnapshot?.groupId===groupId?codeSnapshot.code:'';
 const competitors=data?.members.filter(member=>member.sharing_progress!==false)??[];
 useEffect(()=>subscribePrivacyChange(userId,()=>{setSnapshot(null);setRevision(value=>value+1);}),[userId]);
 useEffect(()=>{if(!owner||displayedCode)return;let active=true;getGroupCode(client,groupId).then(value=>{if(active){setCodeSnapshot({groupId,code:displayGroupCode(value)});setCodeError('');}}).catch(()=>{if(active)setCodeError('Could not load the Group Code. Please retry.');});return()=>{active=false;};},[client,groupId,owner,displayedCode,revision]);
 const reload=useCallback(async()=>{try{setGroups(await listGroups(client));setError('');}catch(e){setError(groupError(e));}finally{setLoading(false);}},[client]);
 useEffect(()=>{let active=true;listGroups(client).then(value=>{if(active){setGroups(value);setLoading(false);}}).catch(e=>{if(active){setError(groupError(e));setLoading(false);}});client.from('profiles').select('display_name').eq('user_id',userId).single().then(({data:profile})=>{if(active&&profile?.display_name&&!profile.display_name.includes('@'))setDisplayName(current=>current||profile.display_name);});return()=>{active=false;};},[client,userId]);
 useEffect(()=>{if(!groupId)return;let active=true;loadGroupSummary(client,groupId,period,timezone,activity).then(value=>{if(active){setSnapshot({key,data:value});setError('');}}).catch(e=>{if(active){setSnapshot(null);setError(groupError(e));}});return()=>{active=false;};},[client,groupId,period,timezone,activity,key]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')setRevision(value=>value+1);};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);
 const open=(kind:string,memberId?:string,label?:string)=>{if(kind==='create')creationRequest.current=crypto.randomUUID();setError('');setName(kind==='rename'?data?.name??'':'');setConsent(false);setDialog({kind,memberId,label});};
 const run=async()=>{
  if(!dialog||busy)return;
  if(['create','join'].includes(dialog.kind)&&(!consent||!displayName.trim()||displayName.includes('@'))){setError('Enter a display name (not an email) and confirm joining this group.');return;}
  setBusy(true);setError('');
  try{
   if(dialog.kind==='create'||dialog.kind==='join'){
    const creating=dialog.kind==='create';
    const created=creating?await createGroup(client,name,displayName,creationRequest.current):null;
    const id=created?.group_id??await joinGroup(client,code,displayName);
    setSelected(id);setSnapshot(null);setActivity('');setHidden([]);setCodeSnapshot(created?{groupId:id,code:displayGroupCode(created.code)}:null);setCodeError('');setNotice('');setCode('');
   }
   else if(dialog.kind==='replace'){const next=await replaceGroupCode(client,groupId);setCodeSnapshot({groupId,code:displayGroupCode(next)});setNotice('Group Code replaced. The old code no longer works.');}
   else {await manageGroup(client,groupId,dialog.kind,dialog.memberId,name);if(['leave','delete'].includes(dialog.kind)){setSelected('');setSnapshot(null);setCodeSnapshot(null);}}
   setDialog(null);setRevision(value=>value+1);await reload();
  }catch(e){setError(groupError(e));}finally{setBusy(false);}
 };
 const members=competitors.filter(member=>!hidden.includes(member.member_id)),bars=muscleCategories.map(muscle=>({muscle,...Object.fromEntries(members.map(member=>[member.member_id,Number(data?.sets.find(row=>row.member_id===member.member_id&&row.muscle===muscle)?.total??0)]))}));
 return <section><p className="eyebrow">PRIVATE GROUPS</p><h1 className="page-title">Leaderboards</h1><p className="mt-2 text-sm">Compete with your group using shared totals. Notes, locations and Bodyweight stay private.</p>
  <div className="mt-5 flex flex-wrap gap-2"><button className="primary-button" onClick={()=>open('create')}>Create Group</button><button className="secondary-button" onClick={()=>open('join')}>Join a Group</button></div>
  {error&&!dialog&&<p className="surface-card mt-4" role="alert">{error} <button className="text-button" onClick={()=>{void reload();setRevision(value=>value+1);}}>Retry</button></p>}
  {loading?<p role="status">Loading groups…</p>:!groups.length?<div className="empty-card">No groups yet. Create a private group or join with a Group Code.</div>:<>
   <div className="primary-filters mt-5 grid gap-3 sm:grid-cols-2"><Select label="Group" value={groupId} options={groups.map(group=>({value:group.id,label:group.name}))} onChange={value=>{setSelected(value);setCodeSnapshot(null);setCodeError('');setNotice('');setHidden([]);setActivity('');}}/><Select label="Time Period" value={period} options={groupPeriods} onChange={setPeriod}/></div>
   {!data&&!error?<p role="status">Loading group totals…</p>:data&&<>
    <div className="surface-card mt-5"><h2 className="text-xl font-bold text-ink">{data.name}</h2><p className="text-sm">{data.members.length} members · Your role: {owner?'Owner':'Member'}</p><p className="mt-2 text-xs">Calendar periods use {timezone}; weeks begin Monday.</p>
     {owner?<details className="mt-3"><summary className="cursor-pointer font-bold">Manage group</summary><div className="mt-3 flex flex-wrap gap-2"><button className="text-button" onClick={()=>open('rename')}>Rename</button><button className="text-button" onClick={()=>open('replace')}>Replace Group Code</button><button className="text-button text-red" onClick={()=>open('delete')}>Delete Group</button></div></details>:<button className="secondary-button mt-3" onClick={()=>open('leave')}>Leave Group</button>}
     {owner&&<div className="group-code-card mt-3"><strong>{data.name}</strong>{displayedCode?<><label className="field-label mt-2">Group Code<input readOnly className="group-code-value" aria-label="Group Code" value={displayedCode}/></label><p className="mt-2 text-sm">Friends can enter this code in Progressive Overload to join.</p><div className="mt-3 flex flex-wrap gap-2"><button className="primary-button" onClick={async()=>setNotice(await copyGroupCode(displayedCode))}>Copy Code</button><button className="secondary-button" onClick={async()=>setNotice(await shareGroupCode(data.name,displayedCode))}>Share Code</button></div></>:codeError?<p role="alert">{codeError} <button className="text-button" onClick={()=>setRevision(value=>value+1)}>Retry</button></p>:<p role="status">Loading Group Code...</p>}</div>}
     {notice&&<p className="mt-3 text-sm" role="status">{notice}</p>}
     <details className="mt-3"><summary className="cursor-pointer font-bold">Members</summary><ul>{data.members.map(member=><li className="flex items-center justify-between gap-2 border-b py-2" key={member.member_id}><span>{member.display_name}{member.is_self?' (you)':''} · {member.role}{member.sharing_progress===false?' - Progress hidden':''}</span>{owner&&!member.is_self&&<button className="text-button text-red" onClick={()=>open('remove',member.member_id,member.display_name)}>Remove</button>}</li>)}</ul></details>
    </div>
    <div className="mt-5 flex gap-2" role="tablist" aria-label="Leaderboard module">{(['strength','cardio'] as const).map(value=><button key={value} role="tab" aria-selected={tab===value} className={tab===value?'primary-button':'secondary-button'} onClick={()=>setTab(value)}>{value==='strength'?'Strength':'Cardio'}</button>)}</div>
    {tab==='strength'?<>
     <div className="surface-card mt-4"><h3 className="font-bold text-ink">Most sets</h3>{strengthRanks(data).map(member=><p className="flex justify-between border-b py-2 text-sm" key={member.member_id}><span>{member.rank}{member.tied?' =':''}. {member.display_name}</span><strong>{member.value} sets</strong></p>)}{!data.sets.length&&<p className="mt-3">No saved sets in this calendar period.</p>}</div>
     <div className="surface-card mt-4"><h3 className="font-bold text-ink">Sets by primary muscle group</h3><details className="my-3"><summary>Show/hide members</summary>{competitors.map((member,index)=><label className="mr-3 inline-flex items-center gap-1 text-xs" key={member.member_id}><input type="checkbox" checked={!hidden.includes(member.member_id)} onChange={()=>setHidden(current=>current.includes(member.member_id)?current.filter(id=>id!==member.member_id):[...current,member.member_id])}/><span style={{color:colors[index%colors.length]}}>{member.display_name}</span></label>)}</details><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={bars} layout="vertical" margin={{left:0,right:10}}><XAxis type="number" allowDecimals={false}/><YAxis dataKey="muscle" type="category" width={85} tick={{fontSize:10}}/><Tooltip formatter={(value,name)=>[`${value} sets`,data.members.find(member=>member.member_id===String(name))?.display_name??'Member']}/>{members.map(member=><Bar key={member.member_id} dataKey={member.member_id} stackId="sets" fill={colors[competitors.indexOf(member)%colors.length]}/>)}</BarChart></ResponsiveContainer></div><details><summary>Accessible counts</summary>{competitors.map(member=><p className="my-2 text-xs" key={member.member_id}><strong>{member.display_name}: </strong>{muscleCategories.map(muscle=>`${muscle} ${data.sets.find(row=>row.member_id===member.member_id&&row.muscle===muscle)?.total??0}`).join(' · ')}</p>)}</details></div>
     <div className="surface-card mt-4"><h3 className="font-bold text-ink">PR races · {new Date(data.through).toLocaleDateString(undefined,{month:'long',year:'numeric',timeZone:timezone})}</h3><p className="text-xs">Calendar month to date, using all earlier performances. First Entry is excluded.</p>{(['weight','reps','combined'] as const).map(kind=><div className="mt-4" key={kind}><h4 className={kind==='weight'?'pr-weight':kind==='reps'?'pr-reps':'font-bold'}>Most {kind==='weight'?'Weight PRs':kind==='reps'?'Rep PRs':'combined PRs'} this month</h4>{strengthRanks(data,kind).map(member=><p className="flex justify-between py-1 text-sm" key={member.member_id}><span>{member.rank}{member.tied?' =':''}. {member.display_name}</span><strong>{member.value}</strong></p>)}</div>)}</div>
    </>:<div className="surface-card mt-4"><div className="grid gap-3 sm:grid-cols-2"><Select label="Activity" value={activity} options={[{value:'',label:'All compatible activities'},...data.activities.map(value=>({value,label:value}))]} onChange={setActivity}/><Select label="Rank by" value={metric} options={[{value:'duration',label:'Total duration'},{value:'distance',label:'Total distance'}]} onChange={value=>setMetric(value as typeof metric)}/></div><p className="mt-3 text-xs">Duration compares time across activities. Distance includes only recorded compatible length units; activities without distance remain unranked.</p>{cardioRanks(data,metric).map(member=><div className="border-b py-3" key={member.member_id}><div className="flex justify-between text-sm"><strong>{member.rank??'—'}{member.tied?' =':''}. {member.display_name}</strong><strong>{metric==='duration'?formatMetric(member.duration,'duration'):member.distance===null?'Not tracked':`${Number((member.distance/1000).toFixed(3))} km`}</strong></div><p className="text-xs">{formatMetric(member.duration,'duration')} · {member.distance===null?'Distance not tracked':`${Number((member.distance/1000).toFixed(3))} km`} · {member.entries} entries</p><p className="text-xs capitalize">{member.activities}</p></div>)}{!data.cardio.length&&<p>No Cardio entries in this period.</p>}</div>}
   </>}
  </>}
  <ConfirmDialog open={!!dialog} title={dialog?.kind==='create'?'Create Group':dialog?.kind==='join'?'Join a Group':dialog?.kind==='remove'?`Remove ${dialog.label}?`:dialog?.kind==='rename'?'Rename Group':dialog?.kind==='replace'?'Replace Group Code?':dialog?.kind==='leave'?'Leave Group?':'Delete Group?'} description={['create','join'].includes(dialog?.kind??'')?'Group members will see your display name. Progress sharing follows your account privacy setting. Notes, locations and Bodyweight stay private.':dialog?.kind==='replace'?'The old code will stop working. Existing members keep their access.':'This affects group access only. Personal activity records are never deleted.'} confirmLabel={dialog?.kind==='create'?'Create Group':dialog?.kind==='join'?'Join Group':dialog?.kind==='rename'?'Save':dialog?.kind==='delete'?'Delete Group':'Continue'} busy={busy} error={error} destructive={['delete','leave','remove'].includes(dialog?.kind??'')} onCancel={()=>{setDialog(null);setError('');}} onConfirm={run}>
   {['create','rename'].includes(dialog?.kind??'')&&<label className="field-label">Group name<input className="field-input" maxLength={80} value={name} onChange={event=>setName(event.target.value)}/></label>}
   {dialog?.kind==='join'&&<label className="field-label">Group Code<input className="field-input" style={{textTransform:'uppercase'}} name="group-code" autoComplete="one-time-code" autoCapitalize="characters" spellCheck={false} inputMode="text" value={code} onChange={event=>setCode(event.target.value)}/></label>}
   {['create','join'].includes(dialog?.kind??'')&&<><label className="field-label mt-3">Display name<input className="field-input" maxLength={80} value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/>I agree to join this private group using my account privacy setting.</label></>}
  </ConfirmDialog>
 </section>;
}
