// Codes are generated by migration 010, never generated or shortened in the client.
export const invalidGroupCode = 'Unable to join with this code. Ask the owner for a current Group Code and try again.';
export function normalizeGroupCode(input: string): string {
  return input.replace(/[\s-]/g, '').toUpperCase();
}
export function displayGroupCode(token: string): string {
  const canonical = normalizeGroupCode(token);
  if (!/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8}$/.test(canonical)) throw new Error(invalidGroupCode);
  return canonical.slice(0,4)+'-'+canonical.slice(4);
}
type Sharing = {clipboard?: Pick<Clipboard, 'writeText'>; share?: (data: ShareData) => Promise<void>};
export async function copyGroupCode(code: string, platform: Sharing = navigator) {
  try {
    if (!platform.clipboard) throw new Error('Clipboard unavailable');
    await platform.clipboard.writeText(displayGroupCode(code));
    return 'Code copied.';
  } catch { return 'Select the Group Code and copy it.'; }
}
export async function shareGroupCode(name: string, code: string, platform: Sharing = navigator) {
  if (platform.share) {
    try { await platform.share({title: name, text: `Join ${name} in Progressive Overload. Group Code: ${displayGroupCode(code)}`}); return 'Code shared.'; }
    catch (error) { if ((error as {name?:string})?.name === 'AbortError') return 'Sharing canceled.'; }
  }
  return copyGroupCode(code, platform);
}
