import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {getProgressSharing,saveProgressSharing,subscribePrivacyChange} from './privacy';
export function ProgressPrivacy(props:{client:SupabaseClient;userId:string}){return <PrivacySetting key={props.userId} {...props}/>;}
function PrivacySetting({client,userId}:{client:SupabaseClient;userId:string}){
 const [enabled,setEnabled]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>subscribePrivacyChange(userId,()=>setRevision(value=>value+1)),[userId]);
 useEffect(()=>{let active=true;getProgressSharing(client).then(value=>{if(active){setEnabled(value);setError('');}}).catch(()=>{if(active)setError('Could not load your sharing preference. Please retry.');});return()=>{active=false;};},[client,revision]);
 const save=async()=>{if(enabled===null||busy)return;setBusy(true);setError('');setNotice('');try{const value=await saveProgressSharing(client,userId,!enabled);setEnabled(value);setNotice(value?'Your progress is shared with your groups.':'Your progress is hidden from all group Leaderboards.');}catch{setError('Your preference could not be saved. Please retry.');}finally{setBusy(false);}};
 return <section className="surface-card mt-4" aria-labelledby="groups-privacy-title"><h2 id="groups-privacy-title" className="font-bold">Groups &amp; Privacy</h2><div className="mt-3 flex items-center justify-between gap-3"><label id="progress-sharing-label" className="font-bold text-sm">Share my progress with groups</label><button type="button" role="switch" aria-labelledby="progress-sharing-label" aria-describedby="progress-sharing-description" aria-checked={enabled??true} disabled={enabled===null||busy} className="privacy-switch" onClick={()=>void save()}><span className={`toggle ${enabled!==false?'toggle-on':''}`} aria-hidden="true"><span/></span></button></div><p id="progress-sharing-description" className="mt-2 text-sm">When turned off, your workout totals and progress will not appear in any group Leaderboards. Your private workout data is never shared.</p>{enabled===null&&!error&&<p role="status">Loading privacy preference...</p>}{busy&&<p role="status">Saving...</p>}{notice&&<p className="mt-2 text-sm" role="status">{notice}</p>}{error&&<p className="mt-2 text-sm" role="alert">{error} <button className="text-button" onClick={()=>enabled===null?setRevision(value=>value+1):void save()}>Retry</button></p>}</section>;
}
