import {normalizeGroupCode,invalidGroupCode} from './groupCode';
import type { SupabaseClient } from '@supabase/supabase-js';
export type Group={id:string;name:string};
export type Member={member_id:string;display_name:string;role:'owner'|'member';is_self:boolean;sharing_progress?:boolean};
export type GroupSummary={name:string;timezone:string;period_start:string;month_start:string;through:string;members:Member[];sets:{member_id:string;muscle:string;total:number}[];prs:{member_id:string;weight_prs:number;rep_prs:number}[];cardio:{member_id:string;activity:string;entries:number;duration_seconds:number;distance_meters:number|null;distance_entries:number}[];activities:string[]};
export async function listGroups(client:SupabaseClient){const {data,error}=await client.from('groups').select('id,name').order('name');if(error)throw error;return (data??[]) as Group[];}
export async function createGroup(client:SupabaseClient,name:string,displayName:string,requestId:string){const {data,error}=await client.rpc('create_private_group_with_code',{p_name:name,p_display_name:displayName,p_request_id:requestId});if(error)throw error;if(!data?.ok||!data.group_id||!data.code)throw new Error('Could not create the group. Please retry.');return data as {group_id:string;code:string};}
export async function joinGroup(client:SupabaseClient,code:string,displayName:string){const {data,error}=await client.rpc('join_private_group_code',{p_code:normalizeGroupCode(code),p_display_name:displayName});if(error){if(error.code==='P0001'||/invite/i.test(error.message))throw {code:error.code,message:invalidGroupCode};throw error;}if(!data?.ok||!data.group_id)throw {message:invalidGroupCode};return data.group_id as string;}
export async function manageGroup(client:SupabaseClient,groupId:string,action:string,memberId?:string,name?:string){const {data,error}=await client.rpc('manage_private_group',{p_group_id:groupId,p_action:action,p_member_id:memberId??null,p_name:name??null});if(error)throw error;return data as {code?:string;expires_at?:string};}
export async function loadGroupSummary(client:SupabaseClient,groupId:string,period:string,timezone:string,activity=''){const {data,error}=await client.rpc('private_group_summary',{p_group_id:groupId,p_period:period,p_timezone:timezone,p_activity:activity});if(error)throw error;return data as GroupSummary;}
export function groupError(error:unknown){const value=error as {code?:string;message?:string;status?:number};if(value?.status===401||['PGRST301','session_not_found','bad_jwt'].includes(value?.code??''))return 'Your session has expired. Sign out and sign in again.';if(['42P01','42703','PGRST202','PGRST205'].includes(value?.code??''))return 'Groups is awaiting its latest update. Please try again later.';if(value?.code==='42501')return 'Group unavailable. You may have been removed, or this action requires the owner.';if(value?.message===invalidGroupCode||/invite/i.test(value?.message??''))return invalidGroupCode;if(/Could not create the group|Could not replace the code|owner|display name|group name|Member no longer/i.test(value?.message??''))return value.message!;return 'Could not reach your groups. Check your connection and retry.';}

export async function getGroupCode(client:SupabaseClient,groupId:string){const {data,error}=await client.rpc('get_private_group_code',{p_group_id:groupId});if(error)throw error;return data as string;}
export async function replaceGroupCode(client:SupabaseClient,groupId:string){const {data,error}=await client.rpc('replace_private_group_code',{p_group_id:groupId});if(error)throw error;if(!data?.ok||!data.code)throw new Error('Could not replace the code. Please retry later.');return data.code as string;}
