import type { SupabaseClient } from '@supabase/supabase-js';
export type Group={id:string;name:string};
export type Member={member_id:string;display_name:string;role:'owner'|'member';is_self:boolean};
export type GroupSummary={name:string;timezone:string;period_start:string;month_start:string;through:string;members:Member[];sets:{member_id:string;muscle:string;total:number}[];prs:{member_id:string;weight_prs:number;rep_prs:number}[];cardio:{member_id:string;activity:string;entries:number;duration_seconds:number;distance_meters:number|null;distance_entries:number}[];activities:string[]};
export async function listGroups(client:SupabaseClient){const {data,error}=await client.from('groups').select('id,name').order('name');if(error)throw error;return (data??[]) as Group[];}
export async function createGroup(client:SupabaseClient,name:string,displayName:string){const {data,error}=await client.rpc('create_private_group',{p_name:name,p_display_name:displayName});if(error)throw error;return data as string;}
export async function joinGroup(client:SupabaseClient,code:string,displayName:string){const {data,error}=await client.rpc('join_private_group',{p_code:code,p_display_name:displayName});if(error)throw error;return data as string;}
export async function manageGroup(client:SupabaseClient,groupId:string,action:string,memberId?:string,name?:string){const {data,error}=await client.rpc('manage_private_group',{p_group_id:groupId,p_action:action,p_member_id:memberId??null,p_name:name??null});if(error)throw error;return data as {code?:string;expires_at?:string};}
export async function loadGroupSummary(client:SupabaseClient,groupId:string,period:string,timezone:string,activity=''){const {data,error}=await client.rpc('private_group_summary',{p_group_id:groupId,p_period:period,p_timezone:timezone,p_activity:activity});if(error)throw error;return data as GroupSummary;}
export function groupError(error:unknown){const value=error as {code?:string;message?:string};if(['42P01','42703','PGRST202','PGRST205'].includes(value?.code??''))return 'Groups needs migration 009 before it can load.';if(value?.code==='42501')return 'Group unavailable. You may have been removed, or this action requires the owner.';if(/invite/i.test(value?.message??''))return 'Invite invalid, expired, exhausted or revoked. Ask the owner for a new code.';if(/owner|display name|group name|Member no longer/i.test(value?.message??''))return value.message!;return 'Could not reach your groups. Check your connection and retry.';}
