import { useMemo, useState, type CSSProperties, type ReactNode } from 'react'

type ModuleKey = 'strength' | 'cardio' | 'mobility' | 'weight'
type Screen = 'home' | ModuleKey | 'progress' | 'settings'
type ModuleState = Record<ModuleKey, boolean>

const modules: Record<ModuleKey, { label: string; icon: string; blurb: string; color: string }> = {
  strength: { label: 'Strength', icon: 'dumbbell', blurb: 'Sets, reps & actual PRs', color: '#b9ff35' },
  cardio: { label: 'Cardio', icon: 'pulse', blurb: 'Runs, rides & intervals', color: '#45d9ff' },
  mobility: { label: 'Mobility', icon: 'spark', blurb: 'Flows, holds & recovery', color: '#bd8cff' },
  weight: { label: 'Weight', icon: 'scale', blurb: 'Bodyweight trends', color: '#ffb84d' },
}

const paths: Record<string, ReactNode> = {
  home: <><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></>,
  dumbbell: <><path d="M6 7v10M3.5 9v6M18 7v10M20.5 9v6M6 12h12"/></>,
  pulse: <path d="M3 12h4l2-6 4 12 2-6h6"/>, spark: <><path d="M12 3v4M12 17v4M3 12h4M17 12h4"/><path d="m5.6 5.6 2.8 2.8M15.6 15.6l2.8 2.8M18.4 5.6l-2.8 2.8M8.4 15.6l-2.8 2.8"/></>,
  scale: <><path d="M5 4h14a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M8 9a4 4 0 0 1 8 0M12 9l2-2"/></>,
  chart: <><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></>, settings: <><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2.2l-2.2 2.2A2 2 0 0 0 15 19l-1 .4V22h-4v-2.6L9 19a2 2 0 0 0-2.2.4l-2.2-2.2A2 2 0 0 0 5 15l-.4-1H2v-4h2.6L5 9a2 2 0 0 0-.4-2.2l2.2-2.2A2 2 0 0 0 9 5l1-.4V2h4v2.6l1 .4a2 2 0 0 0 2.2-.4l2.2 2.2A2 2 0 0 0 19 9l.4 1H22v4h-2.6Z"/></>,
  plus: <path d="M12 5v14M5 12h14"/>, arrow: <path d="m9 18 6-6-6-6"/>, check: <path d="m5 12 4 4L19 6"/>, close: <path d="m6 6 12 12M18 6 6 18"/>,
  trophy: <><path d="M8 4h8v5a4 4 0 0 1-8 0V4Z"/><path d="M8 6H5v2a3 3 0 0 0 3 3M16 6h3v2a3 3 0 0 1-3 3M12 13v4M8 21h8M9 17h6"/></>,
}
function Icon({ name, size = 22 }: { name: string; size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg> }
function Logo() { return <div className="flex items-center gap-3"><span className="grid size-9 rotate-3 place-items-center rounded-xl bg-lime text-navy shadow-glow"><Icon name="pulse" size={21}/></span><span className="font-display text-xl font-extrabold tracking-tight text-white">Peak<span className="text-lime">Form</span></span></div> }
const moduleStyle = (color: string) => ({ '--module-color': color } as CSSProperties)

function Onboarding({ finish }: { finish: (state: ModuleState) => void }) {
  const [step, setStep] = useState(0)
  const [enabled, setEnabled] = useState<ModuleState>({ strength: true, cardio: true, mobility: false, weight: true })
  return <main className="onboarding-shell"><div className="absolute left-6 top-6"><Logo/></div>{step === 0 ? <div className="onboarding-card text-center"><div className="mx-auto mb-8 grid size-24 rotate-3 place-items-center rounded-[2rem] bg-lime text-navy shadow-glow-lg"><Icon name="pulse" size={48}/></div><p className="eyebrow">YOUR TRAINING, YOUR WAY</p><h1 className="mt-3 font-display text-5xl font-black leading-[.95] tracking-[-.05em] text-white sm:text-6xl">Build momentum.<br/><span className="text-lime">See progress.</span></h1><p className="mx-auto mt-6 max-w-md text-base leading-relaxed text-slate-400">A focused home for every rep, run, stretch, and milestone. No noise—just your next win.</p><button className="primary-button mt-9 w-full max-w-sm" onClick={()=>setStep(1)}>Set up PeakForm <Icon name="arrow"/></button><p className="mt-5 text-xs text-slate-600">Takes less than a minute</p></div> : <div className="onboarding-card w-full max-w-2xl"><p className="eyebrow">ONE QUICK STEP</p><h1 className="mt-3 font-display text-4xl font-black tracking-tight text-white">What do you want to track?</h1><p className="mt-3 text-slate-400">Pick your focus. Change this anytime in Settings.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{(Object.keys(modules) as ModuleKey[]).map(key=>{const item=modules[key]; return <button key={key} onClick={()=>setEnabled({...enabled,[key]:!enabled[key]})} className={`module-pick ${enabled[key]?'module-pick-active':''}`} style={moduleStyle(item.color)}><span className="module-icon"><Icon name={item.icon}/></span><span className="flex-1 text-left"><strong className="block text-white">{item.label}</strong><small className="text-slate-500">{item.blurb}</small></span><span className={`check ${enabled[key]?'check-active':''}`}>{enabled[key]&&<Icon name="check" size={14}/>}</span></button>})}</div><button disabled={!Object.values(enabled).some(Boolean)} className="primary-button mt-7 w-full" onClick={()=>finish(enabled)}>Start tracking <Icon name="arrow"/></button><p className="mt-4 text-center text-xs text-slate-600">Choices affect navigation only. Your data is always safe.</p></div>}</main>
}

function Home({ enabled, go, add }: { enabled: ModuleState; go: (s: Screen)=>void; add: ()=>void }) {
  return <section><p className="eyebrow">SUNDAY, AUG 30</p><h1 className="page-title">Hey, athlete <span className="inline-block animate-wave">👋</span></h1><p className="mt-2 text-sm text-slate-400">Ready to make today count?</p><div className="hero-card mt-8"><div className="relative z-10 max-w-md"><span className="eyebrow text-navy/60">TODAY'S MOVE</span><h2 className="mt-2 font-display text-3xl font-black leading-tight text-navy">Every session is a vote for your strongest self.</h2><button className="mt-6 inline-flex items-center gap-2 rounded-xl bg-navy px-5 py-3 text-sm font-extrabold text-white" onClick={add}><Icon name="plus" size={19}/> Log something</button></div><div className="hero-rings"/></div><div className="mt-9"><p className="eyebrow">YOUR MODULES</p><h2 className="mt-1 font-display text-xl font-bold text-white">Pick up where you left off</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(Object.keys(modules) as ModuleKey[]).filter(k=>enabled[k]).map(key=>{const item=modules[key];return <button key={key} className="module-card" onClick={()=>go(key)} style={moduleStyle(item.color)}><span className="module-icon"><Icon name={item.icon}/></span><span className="mt-5 block text-left"><strong className="block font-display text-lg text-white">{item.label}</strong><small className="mt-1 block text-slate-500">No entries yet</small></span><span className="absolute right-4 top-4 text-slate-600"><Icon name="arrow" size={18}/></span></button>})}</div><div className="mt-8 grid gap-4 lg:grid-cols-[1fr_.7fr]"><div className="surface-card"><div className="flex justify-between"><div><p className="eyebrow">THIS WEEK</p><h3 className="mt-1 font-display text-lg font-bold text-white">Activity</h3></div><span className="text-xs text-slate-500">0 sessions</span></div><div className="mt-7 flex h-24 items-end gap-3">{['M','T','W','T','F','S','S'].map((d,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-md bg-white/[.04]" style={{height:24+(i%3)*12}}/><span className="text-[10px] font-bold text-slate-600">{d}</span></div>)}</div></div><div className="surface-card flex items-center gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-lime/10 text-lime"><Icon name="trophy"/></span><div><p className="eyebrow">NEXT MILESTONE</p><h3 className="mt-1 text-sm font-bold text-white">Your first logged workout</h3><p className="mt-1 text-xs text-slate-500">One entry away</p></div></div></div></section>
}

function EmptyScreen({ screen, add }: { screen: Exclude<Screen,'home'|'settings'>; add:()=>void }) {
  const item = screen==='progress' ? {label:'Progress',icon:'chart'} : modules[screen]
  const detail = screen==='strength' ? 'Track sets and reps. PRs here will only reflect actual weight, rep, and relevant distance or lap achievements.' : screen==='progress' ? 'Charts and milestones will appear as you log activity.' : `Log your first ${item.label.toLowerCase()} entry to get started.`
  return <section><p className="eyebrow">{screen==='progress'?'THE BIG PICTURE':'TRAINING MODULE'}</p><h1 className="page-title">{item.label}</h1><div className="empty-card"><div className="empty-icon"><Icon name={item.icon} size={34}/></div><h2 className="font-display text-2xl font-bold text-white">Nothing here yet</h2><p className="mt-2 max-w-md text-sm leading-relaxed text-slate-400">{detail}</p>{screen!=='progress'&&<button className="primary-button mt-6" onClick={add}><Icon name="plus"/> Add {item.label} entry</button>}</div></section>
}

function Settings({ enabled, change }: { enabled:ModuleState; change:(s:ModuleState)=>void }) {
  return <section><p className="eyebrow">MAKE IT YOURS</p><h1 className="page-title">Settings</h1><div className="mt-7 max-w-2xl"><div className="surface-card"><h2 className="font-display text-lg font-bold text-white">Training modules</h2><p className="mt-1 text-sm text-slate-500">Choose what appears in navigation and the Add menu.</p><div className="mt-6 divide-y divide-white/[.06]">{(Object.keys(modules) as ModuleKey[]).map(key=>{const item=modules[key];return <div className="flex items-center gap-4 py-4 first:pt-0 last:pb-0" key={key}><span className="module-icon" style={moduleStyle(item.color)}><Icon name={item.icon}/></span><div className="flex-1"><strong className="text-sm text-white">{item.label}</strong><p className="text-xs text-slate-500">{item.blurb}</p></div><button role="switch" aria-checked={enabled[key]} aria-label={`Enable ${item.label}`} onClick={()=>change({...enabled,[key]:!enabled[key]})} className={`toggle ${enabled[key]?'toggle-on':''}`}><span/></button></div>})}</div></div><div className="mt-4 rounded-2xl border border-lime/10 bg-lime/[.04] p-4 text-xs leading-relaxed text-slate-400"><strong className="text-lime">Your history stays yours.</strong> Turning off a module only hides it. It never deletes data.</div><div className="surface-card mt-4 flex justify-between text-sm"><span className="text-slate-400">PeakForm</span><span className="text-slate-600">Foundation · v0.1</span></div></div></section>
}

function AddSheet({ enabled, close, pick }: { enabled:ModuleState; close:()=>void; pick:(k:ModuleKey)=>void }) {
  const active=(Object.keys(modules) as ModuleKey[]).filter(k=>enabled[k]); return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-6" onMouseDown={close}><div className="sheet" role="dialog" aria-modal="true" aria-labelledby="add-title" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="eyebrow">QUICK ADD</p><h2 id="add-title" className="mt-1 font-display text-2xl font-black text-white">What did you do?</h2></div><button className="icon-button" onClick={close} aria-label="Close"><Icon name="close" size={19}/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{active.map(key=>{const item=modules[key];return <button className="module-pick" style={moduleStyle(item.color)} key={key} onClick={()=>pick(key)}><span className="module-icon"><Icon name={item.icon}/></span><span className="flex-1 text-left font-bold text-white">{item.label}</span><Icon name="arrow" size={17}/></button>})}</div>{!active.length&&<p className="mt-6 rounded-xl bg-white/5 p-4 text-sm text-slate-400">Enable a module in Settings first.</p>}</div></div>
}

function App() {
  const [onboarded,setOnboarded]=useState(false), [screen,setScreen]=useState<Screen>('home'), [addOpen,setAddOpen]=useState(false)
  const [enabled,setEnabled]=useState<ModuleState>({strength:true,cardio:true,mobility:false,weight:true})
  const nav=useMemo(()=>[{key:'home' as Screen,label:'Home',icon:'home'},...(Object.keys(modules) as ModuleKey[]).filter(k=>enabled[k]).map(k=>({key:k as Screen,label:modules[k].label,icon:modules[k].icon})),{key:'progress' as Screen,label:'Progress',icon:'chart'},{key:'settings' as Screen,label:'Settings',icon:'settings'}],[enabled])
  const go=(s:Screen)=>{setScreen(s);window.scrollTo({top:0,behavior:'smooth'})}
  if(!onboarded)return <Onboarding finish={state=>{setEnabled(state);setOnboarded(true)}}/>
  return <div className="min-h-screen bg-navy text-slate-300"><aside className="sidebar"><Logo/><nav className="mt-10 flex flex-col gap-1">{nav.map(item=><button key={item.key} onClick={()=>go(item.key)} className={`nav-item ${screen===item.key?'nav-active':''}`}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav><div className="mt-auto rounded-2xl border border-white/[.05] bg-white/[.025] p-4"><p className="text-xs font-bold text-white">Keep showing up.</p><p className="mt-1 text-[11px] text-slate-600">Small wins become big changes.</p></div></aside><header className="mobile-header"><Logo/><button onClick={()=>go('settings')} className="icon-button" aria-label="Settings"><Icon name="settings"/></button></header><main className="content">{screen==='home'?<Home enabled={enabled} go={go} add={()=>setAddOpen(true)}/>:screen==='settings'?<Settings enabled={enabled} change={setEnabled}/>:<EmptyScreen screen={screen} add={()=>setAddOpen(true)}/>}</main><button className="floating-add" onClick={()=>setAddOpen(true)}><Icon name="plus" size={25}/><span>Add</span></button><nav className="bottom-nav">{nav.filter(i=>['home','progress','settings'].includes(i.key)).map(item=><button key={item.key} onClick={()=>go(item.key)} className={screen===item.key?'text-lime':'text-slate-600'}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav>{addOpen&&<AddSheet enabled={enabled} close={()=>setAddOpen(false)} pick={key=>{setAddOpen(false);go(key)}}/>}</div>
}
export default App
