import { useState, type FormEvent } from 'react'
import { supabase } from './lib/supabase'

export function AuthScreen() {
  const [mode,setMode]=useState<'sign-in'|'sign-up'>('sign-in'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[displayName,setDisplayName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');const result=mode==='sign-in'?await supabase!.auth.signInWithPassword({email,password}):await supabase!.auth.signUp({email,password,options:{data:{display_name:displayName.trim()||null}}});setBusy(false);if(result.error)setMessage(result.error.message);else if(mode==='sign-up'&&!result.data.session)setMessage('Check your email to confirm your account, then sign in.')}
  return <main className="onboarding-shell"><div className="auth-card"><p className="eyebrow">WELCOME TO PEAKFORM</p><h1 className="mt-2 font-display text-4xl font-black tracking-tight text-white">{mode==='sign-in'?'Ready for your next win?':'Start building momentum.'}</h1><p className="mt-3 text-sm text-slate-400">{mode==='sign-in'?'Sign in to access your training.':'Create an account with email and password.'}</p><form className="mt-7 space-y-4" onSubmit={submit}>{mode==='sign-up'&&<label className="auth-label">Display name<input className="auth-input" value={displayName} onChange={e=>setDisplayName(e.target.value)} autoComplete="name" maxLength={80}/></label>}<label className="auth-label">Email<input className="auth-input" type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label className="auth-label">Password<input className="auth-input" type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='sign-in'?'current-password':'new-password'}/></label>{message&&<p role="status" className="rounded-xl border border-lime/10 bg-lime/[.04] p-3 text-sm text-slate-300">{message}</p>}<button disabled={busy} className="primary-button w-full" type="submit">{busy?'Working…':mode==='sign-in'?'Sign in':'Create account'}</button></form><button className="mt-5 w-full border-0 bg-transparent text-sm font-bold text-slate-400 hover:text-lime" onClick={()=>{setMode(mode==='sign-in'?'sign-up':'sign-in');setMessage('')}}>{mode==='sign-in'?'New here? Create an account':'Already have an account? Sign in'}</button></div></main>
}
export function ConfigurationScreen(){return <main className="onboarding-shell"><div className="auth-card text-center"><p className="eyebrow">SUPABASE SETUP REQUIRED</p><h1 className="mt-2 font-display text-3xl font-black text-white">Connect your project locally</h1><p className="mt-4 text-sm leading-relaxed text-slate-400">Copy <code className="text-lime">.env.example</code> to <code className="text-lime">.env.local</code> and add your project URL and publishable/anon key. A service-role key is not needed.</p></div></main>}
